### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'keys'

### ISSUE THREAD

**Issue by goban** [achillesrasquinha/pipupgrade#100]
#### What's the bug all about?

AttributeError: 'NoneType' object has no attribute 'keys' on:

#### What command led to this issue?

pipupgrade -aV    

#### Logs

```
λ werkstation➜  dirgeable [work/micro-allo/proxy_warmup] at  main !+
→  pipupgrade -aV                                                     [403b152]
2021-04-26 16:31:21,701 | INFO | Environment: {'version': '1.9.0', 'python_version': '3.9.4', 'os': 'Linux-5.11.0-16-generic-x86_64-with-glibc2.33', 'config': {'path': {'BASE': '/home/dirgeable/venv/python-3.9.4/lib/python3.9/site-packages/pipupgrade', 'DATA': '/home/dirgeable/venv/python-3.9.4/lib/python3.9/site-packages/pipupgrade/data', 'CACHE': '/home/dirgeable/.config/pipupgrade', 'JOBS': '/home/dirgeable/venv/python-3.9.4/lib/python3.9/site-packages/pipupgrade/jobs'}}, 'settings': {'settings': {'version': '1.9.0', 'cache_timeout': '86400', 'jobs': '20'}}}
2021-04-26 16:31:21,701 | INFO | Arguments Passed: {'args': (), 'kwargs': {'ARGUMENTS': <class 'inspect._empty'>, 'packages': [], 'ignore': None, 'pip_path': None, 'yes': 0, 'check': 0, 'upgrade_type': ['minor', 'patch'], 'latest': 0, 'format': 'table', 'all': True, 'pip': 0, 'self': False, 'requirements': None, 'pipfile': None, 'interactive': 0, 'project': None, 'git_username': None, 'git_email': None, 'pull_request': False, 'github_access_token': None, 'github_reponame': None, 'github_username': None, 'target_branch': 'master', 'jobs': 20, 'user': 0, 'no_included_requirements': 0, 'no_cache': 0, 'output': None, 'ignore_error': 0, 'force': 0, 'no_color': 0, 'verbose': True}, 'a': <pipupgrade.to_params.<locals>.O object at 0x7f81ea2f25e0>}
Checking...
2021-04-26 16:31:21,704 | INFO | `pip` executables found: ['/home/dirgeable/venv/python-3.9.4/bin/pip', '/home/dirgeable/venv/python-3.9.4/bin/pip3']
2021-04-26 16:31:21,704 | INFO | Using 20 jobs...
2021-04-26 16:31:21,726 | INFO | Fetching installed packages for /home/dirgeable/venv/python-3.9.4/bin/pip...
2021-04-26 16:31:21,726 | INFO | Fetching installed packages for /home/dirgeable/venv/python-3.9.4/bin/pip3...
2021-04-26 16:31:21,726 | INFO | Executing command: /home/dirgeable/venv/python-3.9.4/bin/pip list --format json
2021-04-26 16:31:21,726 | INFO | Executing command: /home/dirgeable/venv/python-3.9.4/bin/pip3 list --format json
2021-04-26 16:31:22,140 | INFO | 18 packages found for /home/dirgeable/venv/python-3.9.4/bin/pip.
2021-04-26 16:31:22,140 | INFO | 18 packages found for /home/dirgeable/venv/python-3.9.4/bin/pip3.
2021-04-26 16:31:22,162 | INFO | Initializing Package {'name': 'backcall', 'version': '0.2.0'} of type <class 'dict'>...
2021-04-26 16:31:22,163 | INFO | Fetching package backcall information from DB...
2021-04-26 16:31:22,162 | INFO | Initializing Package {'name': 'decorator', 'version': '5.0.7'} of type <class 'dict'>...
2021-04-26 16:31:22,163 | INFO | Fetching package decorator information from DB...
2021-04-26 16:31:22,163 | INFO | Initializing Package {'name': 'backcall', 'version': '0.2.0'} of type <class 'dict'>...
2021-04-26 16:31:22,163 | INFO | Initializing Package {'name': 'decorator', 'version': '5.0.7'} of type <class 'dict'>...
2021-04-26 16:31:22,163 | INFO | Initializing Package {'name': 'gunicorn', 'version': '20.1.0'} of type <class 'dict'>...
2021-04-26 16:31:22,163 | INFO | Initializing Package {'name': 'gunicorn', 'version': '20.1.0'} of type <class 'dict'>...
2021-04-26 16:31:22,163 | INFO | Initializing Package {'name': 'ipython', 'version': '7.22.0'} of type <class 'dict'>...
2021-04-26 16:31:22,163 | INFO | Fetching package gunicorn information from DB...
2021-04-26 16:31:22,163 | INFO | Fetching package backcall information from DB...
2021-04-26 16:31:22,163 | INFO | Fetching package decorator information from DB...
2021-04-26 16:31:22,163 | INFO | Fetching package gunicorn information from DB...
2021-04-26 16:31:22,163 | INFO | Initializing Package {'name': 'ipython-genutils', 'version': '0.2.0'} of type <class 'dict'>...
2021-04-26 16:31:22,163 | INFO | Fetching package ipython information from DB...
2021-04-26 16:31:22,163 | INFO | Initializing Package {'name': 'ipython', 'version': '7.22.0'} of type <class 'dict'>...
2021-04-26 16:31:22,163 | INFO | Fetching package ipython-genutils information from DB...
2021-04-26 16:31:22,163 | INFO | Fetching package ipython information from DB...
2021-04-26 16:31:22,163 | INFO | Initializing Package {'name': 'ipython-genutils', 'version': '0.2.0'} of type <class 'dict'>...
2021-04-26 16:31:22,163 | INFO | Initializing Package {'name': 'jedi', 'version': '0.18.0'} of type <class 'dict'>...
2021-04-26 16:31:22,163 | INFO | Initializing Package {'name': 'parso', 'version': '0.8.2'} of type <class 'dict'>...
2021-04-26 16:31:22,163 | INFO | Initializing Package {'name': 'jedi', 'version': '0.18.0'} of type <class 'dict'>...
2021-04-26 16:31:22,163 | INFO | Fetching package ipython-genutils information from DB...
2021-04-26 16:31:22,163 | INFO | Fetching package jedi information from DB...
2021-04-26 16:31:22,163 | INFO | Initializing Package {'name': 'pexpect', 'version': '4.8.0'} of type <class 'dict'>...
2021-04-26 16:31:22,163 | INFO | Initializing Package {'name': 'parso', 'version': '0.8.2'} of type <class 'dict'>...
2021-04-26 16:31:22,164 | INFO | Fetching package jedi information from DB...
2021-04-26 16:31:22,164 | INFO | Fetching package parso information from DB...
2021-04-26 16:31:22,164 | INFO | Fetching package pexpect information from DB...
2021-04-26 16:31:22,163 | INFO | Initializing Package {'name': 'pickleshare', 'version': '0.7.5'} of type <class 'dict'>...
2021-04-26 16:31:22,164 | INFO | Fetching package parso information from DB...
2021-04-26 16:31:22,164 | INFO | Initializing Package {'name': 'pickleshare', 'version': '0.7.5'} of type <class 'dict'>...
2021-04-26 16:31:22,164 | INFO | Fetching package pickleshare information from DB...
2021-04-26 16:31:22,164 | INFO | Initializing Package {'name': 'pip', 'version': '21.1'} of type <class 'dict'>...
2021-04-26 16:31:22,164 | INFO | Initializing Package {'name': 'pip', 'version': '21.1'} of type <class 'dict'>...
2021-04-26 16:31:22,164 | INFO | Initializing Package {'name': 'pipupgrade', 'version': '1.9.0'} of type <class 'dict'>...
2021-04-26 16:31:22,164 | INFO | Fetching package pickleshare information from DB...
2021-04-26 16:31:22,164 | INFO | Fetching package pip information from DB...
2021-04-26 16:31:22,164 | INFO | Fetching package pip information from DB...
2021-04-26 16:31:22,164 | INFO | Fetching package pipupgrade information from DB...
2021-04-26 16:31:22,168 | INFO | Using cached info for package <Package backcall (0.2.0)>.
2021-04-26 16:31:22,168 | INFO | Using cached info for package <Package backcall (0.2.0)>.
2021-04-26 16:31:22,168 | INFO | Using cached info for package <Package decorator (5.0.7)>.
2021-04-26 16:31:22,168 | INFO | Using cached info for package <Package gunicorn (20.1.0)>.
2021-04-26 16:31:22,168 | INFO | Using cached info for package <Package decorator (5.0.7)>.
2021-04-26 16:31:22,168 | INFO | Using cached info for package <Package gunicorn (20.1.0)>.
2021-04-26 16:31:22,168 | INFO | Using cached info for package <Package ipython (7.22.0)>.
2021-04-26 16:31:22,168 | INFO | Using cached info for package <Package ipython-genutils (0.2.0)>.
2021-04-26 16:31:22,169 | INFO | Using cached info for package <Package jedi (0.18.0)>.
2021-04-26 16:31:22,169 | INFO | Using cached info for package <Package ipython (7.22.0)>.
2021-04-26 16:31:22,169 | INFO | Using cached info for package <Package ipython-genutils (0.2.0)>.
2021-04-26 16:31:22,169 | INFO | Initializing Package {'name': 'pkg-resources', 'version': '0.0.0'} of type <class 'dict'>...
2021-04-26 16:31:22,169 | INFO | Using cached info for package <Package parso (0.8.2)>.
2021-04-26 16:31:22,169 | INFO | Fetching package pkg-resources information from DB...
2021-04-26 16:31:22,169 | INFO | Using cached info for package <Package pexpect (4.8.0)>.
2021-04-26 16:31:22,169 | INFO | Using cached info for package <Package parso (0.8.2)>.
2021-04-26 16:31:22,169 | INFO | Using cached info for package <Package pickleshare (0.7.5)>.
2021-04-26 16:31:22,169 | INFO | Using cached info for package <Package jedi (0.18.0)>.
2021-04-26 16:31:22,169 | INFO | Fetching PyPI info for package <Package pkg-resources (0.0.0)>...
2021-04-26 16:31:22,169 | INFO | Using cached info for package <Package pipupgrade (1.9.0)>.
2021-04-26 16:31:22,169 | INFO | Dispatching GET request with arguments ('https://pypi.org/pypi/pkg-resources/json',) and parameters {}.
2021-04-26 16:31:22,169 | INFO | Using cached info for package <Package pickleshare (0.7.5)>.
2021-04-26 16:31:22,169 | INFO | Using cached info for package <Package pip (21.1)>.
2021-04-26 16:31:22,169 | INFO | Initializing Package {'name': 'pexpect', 'version': '4.8.0'} of type <class 'dict'>...
2021-04-26 16:31:22,169 | INFO | Initializing Package {'name': 'prompt-toolkit', 'version': '3.0.18'} of type <class 'dict'>...
2021-04-26 16:31:22,169 | INFO | Using cached info for package <Package pip (21.1)>.
2021-04-26 16:31:22,170 | INFO | Fetching package pexpect information from DB...
2021-04-26 16:31:22,170 | INFO | Fetching package prompt-toolkit information from DB...
2021-04-26 16:31:22,169 | INFO | Initializing Package {'name': 'Pygments', 'version': '2.8.1'} of type <class 'dict'>...
2021-04-26 16:31:22,169 | INFO | Initializing Package {'name': 'setuptools', 'version': '56.0.0'} of type <class 'dict'>...
2021-04-26 16:31:22,170 | INFO | Fetching package Pygments information from DB...
2021-04-26 16:31:22,170 | INFO | Fetching package setuptools information from DB...
2021-04-26 16:31:22,170 | INFO | Initializing Package {'name': 'traitlets', 'version': '5.0.5'} of type <class 'dict'>...
2021-04-26 16:31:22,170 | INFO | Initializing Package {'name': 'pkg-resources', 'version': '0.0.0'} of type <class 'dict'>...
2021-04-26 16:31:22,170 | INFO | Fetching package traitlets information from DB...
2021-04-26 16:31:22,170 | INFO | Initializing Package {'name': 'wcwidth', 'version': '0.2.5'} of type <class 'dict'>...
2021-04-26 16:31:22,170 | INFO | Fetching package pkg-resources information from DB...
2021-04-26 16:31:22,170 | INFO | Initializing Package {'name': 'prompt-toolkit', 'version': '3.0.18'} of type <class 'dict'>...
2021-04-26 16:31:22,170 | INFO | Fetching package wcwidth information from DB...
2021-04-26 16:31:22,170 | INFO | Fetching package prompt-toolkit information from DB...
2021-04-26 16:31:22,170 | INFO | Initializing Package {'name': 'ptyprocess', 'version': '0.7.0'} of type <class 'dict'>...
2021-04-26 16:31:22,170 | INFO | Initializing Package {'name': 'ptyprocess', 'version': '0.7.0'} of type <class 'dict'>...
2021-04-26 16:31:22,170 | INFO | Initializing Package {'name': 'Pygments', 'version': '2.8.1'} of type <class 'dict'>...
2021-04-26 16:31:22,170 | INFO | Fetching package ptyprocess information from DB...
2021-04-26 16:31:22,170 | INFO | Fetching package ptyprocess information from DB...
2021-04-26 16:31:22,170 | INFO | Initializing Package {'name': 'setuptools', 'version': '56.0.0'} of type <class 'dict'>...
2021-04-26 16:31:22,170 | INFO | Fetching package Pygments information from DB...
2021-04-26 16:31:22,171 | INFO | Fetching package setuptools information from DB...
2021-04-26 16:31:22,171 | INFO | Fetching PyPI info for package <Package pkg-resources (0.0.0)>...
2021-04-26 16:31:22,170 | INFO | Initializing Package {'name': 'traitlets', 'version': '5.0.5'} of type <class 'dict'>...
2021-04-26 16:31:22,171 | INFO | Dispatching GET request with arguments ('https://pypi.org/pypi/pkg-resources/json',) and parameters {}.
2021-04-26 16:31:22,171 | INFO | Fetching package traitlets information from DB...
2021-04-26 16:31:22,171 | INFO | Initializing Package {'name': 'wcwidth', 'version': '0.2.5'} of type <class 'dict'>...
2021-04-26 16:31:22,171 | INFO | Using cached info for package <Package ptyprocess (0.7.0)>.
2021-04-26 16:31:22,171 | INFO | Fetching package wcwidth information from DB...
2021-04-26 16:31:22,174 | INFO | Using cached info for package <Package Pygments (2.8.1)>.
2021-04-26 16:31:22,174 | INFO | Using cached info for package <Package traitlets (5.0.5)>.
2021-04-26 16:31:22,174 | INFO | Using cached info for package <Package setuptools (56.0.0)>.
2021-04-26 16:31:22,174 | INFO | Initializing Package {'name': 'pipupgrade', 'version': '1.9.0'} of type <class 'dict'>...
2021-04-26 16:31:22,175 | INFO | Fetching package pipupgrade information from DB...
2021-04-26 16:31:22,175 | INFO | Using cached info for package <Package prompt-toolkit (3.0.18)>.
2021-04-26 16:31:22,175 | INFO | Using cached info for package <Package pexpect (4.8.0)>.
2021-04-26 16:31:22,175 | INFO | Using cached info for package <Package setuptools (56.0.0)>.
2021-04-26 16:31:22,175 | INFO | Using cached info for package <Package wcwidth (0.2.5)>.
2021-04-26 16:31:22,176 | INFO | Using cached info for package <Package Pygments (2.8.1)>.
2021-04-26 16:31:22,176 | INFO | Using cached info for package <Package ptyprocess (0.7.0)>.
2021-04-26 16:31:22,176 | INFO | Using cached info for package <Package traitlets (5.0.5)>.
2021-04-26 16:31:22,176 | INFO | Using cached info for package <Package wcwidth (0.2.5)>.
2021-04-26 16:31:22,177 | INFO | Using cached info for package <Package prompt-toolkit (3.0.18)>.
2021-04-26 16:31:22,179 | INFO | Using cached info for package <Package pipupgrade (1.9.0)>.

multiprocessing.pool.RemoteTraceback: 
"""
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/dirgeable/venv/python-3.9.4/lib/python3.9/site-packages/pipupgrade/model/package.py", line 138, in __init__
    self.releases   = [version for version in iterkeys(_pypi_info.get("releases"))]
  File "/home/dirgeable/venv/python-3.9.4/lib/python3.9/site-packages/pipupgrade/_compat.py", line 41, in iterkeys
    iterator = iter(dict_.keys(), **kwargs)
AttributeError: 'NoneType' object has no attribute 'keys'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/dirgeable/venv/python-3.9.4/lib/python3.9/site-packages/pipupgrade/commands/helper.py", line 332, in get_registry_from_pip
    registry     = Registry(source = pip_path, packages = packages,
  File "/home/dirgeable/venv/python-3.9.4/lib/python3.9/site-packages/pipupgrade/model/registry.py", line 117, in __init__
    for package in pool.imap_unordered(partial(Package, **args), packages):
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 870, in next
    raise value
AttributeError: 'NoneType' object has no attribute 'keys'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dirgeable/venv/python-3.9.4/lib/python3.9/site-packages/pipupgrade/commands/__init__.py", line 78, in command
    return _command(**ARGUMENTS)
  File "/home/dirgeable/venv/python-3.9.4/lib/python3.9/site-packages/pipupgrade/commands/__init__.py", line 222, in _command
    for registry in pool.imap_unordered(
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 870, in next
    raise value
AttributeError: 'NoneType' object has no attribute 'keys'

An error occured while performing the above command. This could be an issue with
"pipupgrade". Kindly post an issue at https://github.com/achillesrasquinha/pipupgrade/issues
```

**Comment by goban** [comment]
note, without -a it works ok
