### ISSUE TITLE
pipupgrade.exception.PopenError: Command '/usr/bin/pip2 install pygobject --no-cache-dir --upgrade' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by jmwislez** [achillesrasquinha/pipupgrade#103]
As requested, I post an issue

Traceback (most recent call last):
  File "/home/jmw/.local/lib/python3.6/site-packages/pipupgrade/commands/__init__.py", line 78, in command
    return _command(**ARGUMENTS)
  File "/home/jmw/.local/lib/python3.6/site-packages/pipupgrade/commands/__init__.py", line 244, in _command
    upgrade_type = a.upgrade_type
  File "/home/jmw/.local/lib/python3.6/site-packages/pipupgrade/commands/helper.py", line 305, in update_registry
    upgrade = True
  File "/home/jmw/.local/lib/python3.6/site-packages/pipupgrade/_pip.py", line 75, in call
    output = popen(*params, output = output, raise_err = raise_err)
  File "/home/jmw/.local/lib/python3.6/site-packages/pipupgrade/util/system.py", line 92, in popen
    raise PopenError(code, command)
pipupgrade.exception.PopenError: Command '/usr/bin/pip2 install pygobject --no-cache-dir --upgrade' returned non-zero exit status 1.

An error occured while performing the above command. This could be an issue with
"pipupgrade". Kindly post an issue at https://github.com/achillesrasquinha/pipupgrade/issues

**Comment by sgreadly** [comment]
Could this be related to Issue #106 ? Try upgrading pip2 and see if this is resolved.

**Comment by HenrikFFM** [comment]
@sgreadly:

not for me.

I habe a fresh WSL Linux 2 Installation, Ubuntu 20

$ sudo apt update
$ sudo apt install python3-pip
$ sudo pip3 install pip --upgrade
$ sudo pip install ansible --upgrade
$ sudo pip install pywinrm --upgrade
$ sudo pip install pipupgrade --upgrade
$ sudo pipupgrade

`sudo pipupgrade
/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
Checking...

Source: Installed Distributions (/usr/local/bin/pip)

Name               Current Version Latest Version Home Page
------------------ --------------- -------------- ---------------------------------------------------------
attrs              19.3.0          21.2.0         https://www.attrs.org/
Automat            0.8.0           20.2.0         https://github.com/glyph/Automat
certifi            2019.11.28      2021.5.30      https://certifiio.readthedocs.io/en/latest/
chardet            3.0.4           4.0.0          https://github.com/chardet/chardet
distro-info        0.23ubuntu1     0.10           UNKNOWN
hyperlink          19.0.0          21.0.0         https://github.com/python-hyper/hyperlink
importlib-metadata 1.5.0           4.6.1          https://github.com/python/importlib_metadata
incremental        16.10.1         21.3.0         https://github.com/twisted/incremental
Jinja2             2.10.1          3.0.1          https://palletsprojects.com/p/jinja/
keyring            18.0.1          23.0.1         https://github.com/jaraco/keyring
MarkupSafe         1.1.0           2.0.1          https://palletsprojects.com/p/markupsafe/
more-itertools     4.2.0           8.8.0          https://github.com/more-itertools/more-itertools
pexpect            4.6.0           4.8.0          https://pexpect.readthedocs.io/
pyasn1             0.4.2           0.4.8          https://github.com/etingof/pyasn1
pyasn1-modules     0.2.1           0.2.8          https://github.com/etingof/pyasn1-modules
PyGObject          3.36.0          3.40.1         https://pygobject.readthedocs.io
PyHamcrest         1.9.0           2.0.2          https://github.com/hamcrest/PyHamcrest
PyJWT              1.7.1           2.1.0          https://github.com/jpadilla/pyjwt
PyNaCl             1.3.0           1.4.0          https://github.com/pyca/pynacl/
pyOpenSSL          19.0.0          20.0.1         https://pyopenssl.org/
pyrsistent         0.15.5          0.18.0         http://github.com/tobgu/pyrsistent/
pyserial           3.4             3.5            https://github.com/pyserial/pyserial
python-debian      0.1.36ubuntu1   0.1.40         https://salsa.debian.org/python-debian-team/python-debian
PyYAML             5.3.1           5.4.1          https://pyyaml.org/
requests           2.22.0          2.25.1         https://requests.readthedocs.io
resolvelib         0.5.4           0.7.1          https://github.com/sarugaku/resolvelib
SecretStorage      2.3.1           3.3.1          https://github.com/mitya57/secretstorage
service-identity   18.1.0          21.1.0         https://service-identity.readthedocs.io/
setuptools         45.2.0          57.1.0         https://github.com/pypa/setuptools
simplejson         3.16.0          3.17.2         https://github.com/simplejson/simplejson
six                1.14.0          1.16.0         https://github.com/benjaminp/six
ssh-import-id      5.10            5.11           https://launchpad.net/ssh-import-id
Twisted            18.9.0          21.2.0         https://twistedmatrix.com/
urllib3            1.25.8          1.26.6         https://urllib3.readthedocs.io/
wadllib            1.3.3           1.3.5          https://launchpad.net/wadllib
wheel              0.34.2          0.36.2         https://github.com/pypa/wheel
zipp               1.0.0           3.5.0          https://github.com/jaraco/zipp
zope.interface     4.7.1           5.4.0          https://github.com/zopefoundation/zope.interface

Do you wish to update 18 packages? [Y/n/q]: Y
Updating 1 of 18 packages: distro-info
Updating 2 of 18 packages: pexpect

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pipupgrade/commands/__init__.py", line 78, in command
    return _command(**ARGUMENTS)
  File "/usr/local/lib/python3.8/dist-packages/pipupgrade/commands/__init__.py", line 240, in _command
    update_registry(registry, yes = a.yes, user = a.user, check = a.check,
  File "/usr/local/lib/python3.8/dist-packages/pipupgrade/commands/helper.py", line 302, in update_registry
    _pip.call("install", package.name,
  File "/usr/local/lib/python3.8/dist-packages/pipupgrade/_pip.py", line 75, in call
    output = popen(*params, output = output, raise_err = raise_err)
  File "/usr/local/lib/python3.8/dist-packages/pipupgrade/util/system.py", line 92, in popen
    raise PopenError(code, command)
pipupgrade.exception.PopenError: Command '/usr/local/bin/pip install pexpect --no-cache-dir --upgrade' returned non-zero exit status 1.

An error occured while performing the above command. This could be an issue with
"pipupgrade". Kindly post an issue at https://github.com/achillesrasquinha/pipupgrade/issues`

**Comment by sgreadly** [comment]
@HenrikFFM 

Can you post the output of 

$ pip2 --version

$ pip2 install -U pip

**Comment by HenrikFFM** [comment]
(base) schuetzeh@WKSFRA005:~$ pip2 --version

Command 'pip2' not found, did you mean:

  command 'pip' from deb python3-pip (20.0.2-5ubuntu1.5)
  command 'pipx' from deb pipx (0.12.3.1-2ubuntu1)
  command 'nip2' from deb nip2 (8.7.0-1)
  command 'pip3' from deb python3-pip (20.0.2-5ubuntu1.5)

Try: sudo apt install <deb name>

(base) schuetzeh@WKSFRA005:~$

**Comment by HenrikFFM** [comment]
(base) schuetzeh@WKSFRA005:~$ pip2 install -U pip

Command 'pip2' not found, did you mean:

  command 'pip' from deb python3-pip (20.0.2-5ubuntu1.5)
  command 'pip3' from deb python3-pip (20.0.2-5ubuntu1.5)
  command 'pipx' from deb pipx (0.12.3.1-2ubuntu1)
  command 'nip2' from deb nip2 (8.7.0-1)

Try: sudo apt install <deb name>

(base) schuetzeh@WKSFRA005:~$

**Comment by HenrikFFM** [comment]
and sometimes i get:

schuetzeh@WKSFRA005:~$ sudo pipupgrade
Checking...
2021-07-08 10:34:06,588 | WARNING | Unable to save package name. UNIQUE constraint failed: tabPackage.name
2021-07-08 10:34:06,642 | WARNING | Unable to save package name. UNIQUE constraint failed: tabPackage.name
2021-07-08 10:34:06,821 | WARNING | Unable to save package name. UNIQUE constraint failed: tabPackage.name
2021-07-08 10:34:06,888 | WARNING | Unable to save package name. UNIQUE constraint failed: tabPackage.name
2021-07-08 10:34:06,919 | WARNING | Unable to save package name. UNIQUE constraint failed: tabPackage.name
2021-07-08 10:34:07,314 | WARNING | Unable to save package name. UNIQUE constraint failed: tabPackage.name
2021-07-08 10:34:07,439 | WARNING | Unable to save package name. UNIQUE constraint failed: tabPackage.name
2021-07-08 10:34:07,510 | WARNING | Unable to save package name. UNIQUE constraint failed: tabPackage.name
2021-07-08 10:34:07,627 | WARNING | Unable to save package name. UNIQUE constraint failed: tabPackage.name
2021-07-08 10:34:07,628 | WARNING | Unable to save package name. UNIQUE constraint failed: tabPackage.name
2021-07-08 10:34:07,630 | WARNING | Unable to save package name. UNIQUE constraint failed: tabPackage.name
2021-07-08 10:34:07,825 | WARNING | Unable to save package name. UNIQUE constraint failed: tabPackage.name
2021-07-08 10:34:07,897 | WARNING | Unable to save package name. UNIQUE constraint failed: tabPackage.name
2021-07-08 10:34:07,900 | WARNING | Unable to save package name. UNIQUE constraint failed: tabPackage.name
2021-07-08 10:34:08,220 | WARNING | Unable to save package name. UNIQUE constraint failed: tabPackage.name
2021-07-08 10:34:08,266 | WARNING | Unable to save package name. UNIQUE constraint failed: tabPackage.name
2021-07-08 10:34:08,300 | WARNING | Unable to save package name. UNIQUE constraint failed: tabPackage.name
2021-07-08 10:34:08,380 | WARNING | Unable to save package name. UNIQUE constraint failed: tabPackage.name
2021-07-08 10:34:08,491 | WARNING | Unable to save package name. UNIQUE constraint failed: tabPackage.name
2021-07-08 10:34:08,497 | WARNING | Unable to save package name. UNIQUE constraint failed: tabPackage.name
2021-07-08 10:34:08,505 | WARNING | Unable to save package name. UNIQUE constraint failed: tabPackage.name
2021-07-08 10:34:16,158 | WARNING | Unable to save package name. database is locked
2021-07-08 10:34:16,463 | WARNING | Unable to save package name. database is locked
2021-07-08 10:34:16,464 | WARNING | Unable to save package name. database is locked
2021-07-08 10:34:16,587 | WARNING | Unable to save package name. database is locked
2021-07-08 10:34:17,691 | WARNING | Unable to save package name. database is locked
2021-07-08 10:34:17,919 | WARNING | Unable to save package name. database is locked
2021-07-08 10:34:17,962 | WARNING | Unable to save package name. database is locked
2021-07-08 10:34:18,267 | WARNING | Unable to save package name. database is locked
2021-07-08 10:34:18,583 | WARNING | Unable to save package name. database is locked
....

**Comment by HenrikFFM** [comment]
#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'pip==20.0.2','console_scripts','pip3'
__requires__ = 'pip==20.0.2'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('pip==20.0.2', 'console_scripts', 'pip3')()
    )
/usr/bin/pip3 (END)
