### ISSUE TITLE
Package update error

### ISSUE THREAD

**Issue by Thabomtt** [achillesrasquinha/pipupgrade#110]
#### What's the bug all about?

*A clear and concise description of what the bug is.*

#### What command led to this issue?

Updating 7 of 49 packages: distro-info
duplicity (0.8.12.0) -> (0.8.20) [Y/n/q]: Y
Updating 8 of 49 packages: duplicity

Traceback (most recent call last):
  File "/home/machine/.local/lib/python3.8/site-packages/pipupgrade/commands/__init__.py", line 78, in command
    return _command(**ARGUMENTS)
  File "/home/machine/.local/lib/python3.8/site-packages/pipupgrade/commands/__init__.py", line 240, in _command
    update_registry(registry, yes = a.yes, user = a.user, check = a.check,
  File "/home/machine/.local/lib/python3.8/site-packages/pipupgrade/commands/helper.py", line 302, in update_registry
    _pip.call("install", package.name,
  File "/home/machine/.local/lib/python3.8/site-packages/pipupgrade/_pip.py", line 75, in call
    output = popen(*params, output = output, raise_err = raise_err)
  File "/home/machine/.local/lib/python3.8/site-packages/pipupgrade/util/system.py", line 92, in popen
    raise PopenError(code, command)
pipupgrade.exception.PopenError: Command '/usr/bin/pip install duplicity --no-cache-dir --upgrade' returned non-zero exit status 1.

*Please type the exact command that led to this issue.*
pipupgrade --latest --interactive

```
$ "<YOUR COMMAND HERE>"
```

#### Logs

*Please paste the logs using `pipupgrade --verbose`*

```
"<YOUR LOGS HERE>"
```

**Comment by achillesrasquinha** [comment]
Could you share the logs?
