### ISSUE TITLE
Error while checking

### ISSUE THREAD

**Issue by machinexa2** [achillesrasquinha/pipupgrade#116]
```python
Checking...

concurrent.futures.process._RemoteTraceback: 
"""
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.9/concurrent/futures/process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/usr/lib/python3.9/concurrent/futures/process.py", line 202, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/usr/lib/python3.9/concurrent/futures/process.py", line 202, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/usr/local/lib/python3.9/dist-packages/pipupgrade/model/package.py", line 129, in __init__
    time_difference	= to_datetime(res["_updated_at"]) + timedelta(seconds = cache_timeout)
  File "/usr/local/lib/python3.9/dist-packages/pipupgrade/model/package.py", line 74, in to_datetime
    return datetime.strptime(string, "%Y-%m-%d %H:%M:%S")
  File "/usr/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.9/_strptime.py", line 352, in _strptime
    raise ValueError("unconverted data remains: %s" %
ValueError: unconverted data remains: .907094
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.9/concurrent/futures/process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/usr/lib/python3.9/concurrent/futures/process.py", line 202, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/usr/lib/python3.9/concurrent/futures/process.py", line 202, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/usr/local/lib/python3.9/dist-packages/pipupgrade/commands/helper.py", line 331, in get_registry_from_pip
    registry     = Registry(source = pip_path, packages = packages,
  File "/usr/local/lib/python3.9/dist-packages/pipupgrade/model/registry.py", line 119, in __init__
    for package in pool.imap_unordered(partial(Package, **args), packages):
  File "/usr/lib/python3.9/concurrent/futures/process.py", line 559, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 600, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 440, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
ValueError: unconverted data remains: .907094
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/pipupgrade/commands/__init__.py", line 77, in command
    return _command(**ARGUMENTS)
  File "/usr/local/lib/python3.9/dist-packages/pipupgrade/commands/__init__.py", line 229, in _command
    for registry in pool.imap_unordered(
  File "/usr/lib/python3.9/concurrent/futures/process.py", line 559, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 600, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 440, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
ValueError: unconverted data remains: .907094

An error occured while performing the above command. This could be an issue with
"pipupgrade". Kindly post an issue at https://github.com/achillesrasquinha/pipupgrade/issues
```
```python
Checking...

concurrent.futures.process._RemoteTraceback: 
"""
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.9/concurrent/futures/process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/usr/lib/python3.9/concurrent/futures/process.py", line 202, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/usr/lib/python3.9/concurrent/futures/process.py", line 202, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/usr/local/lib/python3.9/dist-packages/pipupgrade/model/package.py", line 129, in __init__
    time_difference	= to_datetime(res["_updated_at"]) + timedelta(seconds = cache_timeout)
  File "/usr/local/lib/python3.9/dist-packages/pipupgrade/model/package.py", line 74, in to_datetime
    return datetime.strptime(string, "%Y-%m-%d %H:%M:%S")
  File "/usr/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.9/_strptime.py", line 352, in _strptime
    raise ValueError("unconverted data remains: %s" %
ValueError: unconverted data remains: .907094
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.9/concurrent/futures/process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/usr/lib/python3.9/concurrent/futures/process.py", line 202, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/usr/lib/python3.9/concurrent/futures/process.py", line 202, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/usr/local/lib/python3.9/dist-packages/pipupgrade/commands/helper.py", line 331, in get_registry_from_pip
    registry     = Registry(source = pip_path, packages = packages,
  File "/usr/local/lib/python3.9/dist-packages/pipupgrade/model/registry.py", line 119, in __init__
    for package in pool.imap_unordered(partial(Package, **args), packages):
  File "/usr/lib/python3.9/concurrent/futures/process.py", line 559, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 608, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
ValueError: unconverted data remains: .907094
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/pipupgrade/commands/__init__.py", line 77, in command
    return _command(**ARGUMENTS)
  File "/usr/local/lib/python3.9/dist-packages/pipupgrade/commands/__init__.py", line 229, in _command
    for registry in pool.imap_unordered(
  File "/usr/lib/python3.9/concurrent/futures/process.py", line 559, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 608, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
ValueError: unconverted data remains: .907094

An error occured while performing the above command. This could be an issue with
"pipupgrade". Kindly post an issue at https://github.com/achillesrasquinha/pipupgrade/issues
```
The error occured after pipupgrade --ignore-error

**Comment by achillesrasquinha** [comment]
Fixed with 1.10.1
