### ISSUE TITLE
"An error occured while performing the above command. This could be an issue with "pipupgrade"."

### ISSUE THREAD

**Issue by roeravid** [achillesrasquinha/pipupgrade#122]
#### What's the bug all about?

i dont know enough to say, im sorry! if you contact me i can run through it with you and answer any questions you have as long as you help me find the info you need. 

#### pipupgrade

*Please type the exact command that led to this issue.*

```
$ "<pipupgrade>"
```

#### Logs

*Please paste the logs using `pipupgrade --verbose`*

```
(base) roeravid@Joes-MBP:/Users/roeravid git:(master*) $ pipupgrade --verbose
2021-10-15 21:16:11,182 | INFO | Environment: {'version': '0.2.0', 'python_version': '3.8.8', 'os': 'macOS-10.15.7-x86_64-i386-64bit', 'config': {'path': {'BASE': '/Users/roeravid/opt/anaconda3/lib/python3.8/site-packages/bpyutils', 'DATA': '/Users/roeravid/opt/anaconda3/lib/python3.8/site-packages/bpyutils/data', 'CACHE': '/Users/roeravid/.config/bpyutils', 'JOBS': '/Users/roeravid/opt/anaconda3/lib/python3.8/site-packages/bpyutils/jobs'}}, 'settings': {'settings': {'version': '0.2.0', 'cache_timeout': '86400', 'jobs': '4'}}}
2021-10-15 21:16:11,183 | INFO | Arguments Passed: {'args': (), 'kwargs': {'ARGUMENTS': <class 'inspect._empty'>, 'packages': [], 'resolve': False, 'ignore': None, 'pip_path': None, 'yes': 0, 'clean': 0, 'check': 0, 'upgrade_type': ['minor', 'patch'], 'latest': 0, 'format': 'table', 'all': 0, 'pip': 0, 'self': False, 'requirements': None, 'pipfile': None, 'interactive': 0, 'project': None, 'git_username': None, 'git_email': None, 'pull_request': False, 'github_access_token': None, 'github_reponame': None, 'github_username': None, 'target_branch': 'master', 'jobs': 4, 'user': 0, 'no_included_requirements': 0, 'no_cache': 0, 'output': None, 'ignore_error': 0, 'force': 0, 'doctor': False, 'no_color': 0, 'verbose': True}, 'a': <pipupgrade.commands.to_params.<locals>.O object at 0x7fce0fa9e790>}
Checking...
2021-10-15 21:16:11,191 | INFO | `pip` executables found: ['/Users/roeravid/opt/anaconda3/bin/pip', '/Users/roeravid/opt/anaconda3/bin/pip3', '/usr/local/bin/pip2']
2021-10-15 21:16:11,192 | INFO | Using 4 jobs...
2021-10-15 21:16:13,179 | INFO | Fetching installed packages for /Users/roeravid/opt/anaconda3/bin/pip...
2021-10-15 21:16:13,180 | INFO | Executing command: /Users/roeravid/opt/anaconda3/bin/pip list --outdated --format json
2021-10-15 21:16:13,211 | INFO | Fetching installed packages for /Users/roeravid/opt/anaconda3/bin/pip3...
2021-10-15 21:16:13,212 | INFO | Executing command: /Users/roeravid/opt/anaconda3/bin/pip3 list --outdated --format json
2021-10-15 21:16:13,266 | INFO | Fetching installed packages for /usr/local/bin/pip2...
2021-10-15 21:16:13,268 | INFO | Executing command: /usr/local/bin/pip2 list --outdated --format json
2021-10-15 21:17:09,091 | INFO | 12 packages found for /Users/roeravid/opt/anaconda3/bin/pip.
2021-10-15 21:17:10,294 | INFO | 12 packages found for /Users/roeravid/opt/anaconda3/bin/pip3.
2021-10-15 21:17:13,779 | INFO | Initializing Package {'name': 'astroid', 'version': '2.6.6', 'latest_version': '2.8.2', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2021-10-15 21:17:13,779 | INFO | Fetching package astroid information from DB...
2021-10-15 21:17:13,786 | INFO | Using cached info for package <Package astroid (2.6.6)>.
2021-10-15 21:17:13,787 | INFO | Initializing Package {'name': 'flake8', 'version': '3.9.2', 'latest_version': '4.0.1', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2021-10-15 21:17:13,787 | INFO | Fetching package flake8 information from DB...
2021-10-15 21:17:13,789 | INFO | Using cached info for package <Package flake8 (3.9.2)>.
2021-10-15 21:17:13,789 | INFO | Initializing Package {'name': 'idna', 'version': '2.10', 'latest_version': '3.3', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2021-10-15 21:17:13,789 | INFO | Fetching package idna information from DB...
2021-10-15 21:17:13,790 | INFO | Using cached info for package <Package idna (2.10)>.
2021-10-15 21:17:13,795 | INFO | Initializing Package {'name': 'jedi', 'version': '0.17.2', 'latest_version': '0.18.0', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2021-10-15 21:17:13,795 | INFO | Fetching package jedi information from DB...
2021-10-15 21:17:13,796 | INFO | Using cached info for package <Package jedi (0.17.2)>.
2021-10-15 21:17:13,796 | INFO | Initializing Package {'name': 'jupyter-client', 'version': '6.1.12', 'latest_version': '7.0.6', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2021-10-15 21:17:13,796 | INFO | Fetching package jupyter-client information from DB...
2021-10-15 21:17:13,800 | INFO | Using cached info for package <Package jupyter-client (6.1.12)>.
2021-10-15 21:17:13,801 | INFO | Initializing Package {'name': 'parso', 'version': '0.7.1', 'latest_version': '0.8.2', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2021-10-15 21:17:13,801 | INFO | Fetching package parso information from DB...
2021-10-15 21:17:13,801 | INFO | Using cached info for package <Package parso (0.7.1)>.
2021-10-15 21:17:13,824 | INFO | Initializing Package {'name': 'pycodestyle', 'version': '2.7.0', 'latest_version': '2.8.0', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2021-10-15 21:17:13,824 | INFO | Fetching package pycodestyle information from DB...
2021-10-15 21:17:13,828 | INFO | Using cached info for package <Package pycodestyle (2.7.0)>.
2021-10-15 21:17:13,829 | INFO | Initializing Package {'name': 'pycurl', 'version': '7.43.0.6', 'latest_version': '7.44.1', 'latest_filetype': 'sdist'} of type <class 'dict'>...
2021-10-15 21:17:13,829 | INFO | Fetching package pycurl information from DB...
2021-10-15 21:17:13,830 | INFO | Using cached info for package <Package pycurl (7.43.0.6)>.
2021-10-15 21:17:13,830 | INFO | Initializing Package {'name': 'pyflakes', 'version': '2.3.1', 'latest_version': '2.4.0', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2021-10-15 21:17:13,830 | INFO | Fetching package pyflakes information from DB...
2021-10-15 21:17:13,830 | INFO | Using cached info for package <Package pyflakes (2.3.1)>.
2021-10-15 21:17:13,831 | INFO | Initializing Package {'name': 'pylint', 'version': '2.9.6', 'latest_version': '2.11.1', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2021-10-15 21:17:13,831 | INFO | Fetching package pylint information from DB...
2021-10-15 21:17:13,831 | INFO | Using cached info for package <Package pylint (2.9.6)>.
2021-10-15 21:17:13,832 | INFO | Initializing Package {'name': 'PyQt5', 'version': '5.12.3', 'latest_version': '5.15.4', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2021-10-15 21:17:13,832 | INFO | Fetching package PyQt5 information from DB...
2021-10-15 21:17:13,832 | INFO | Using cached info for package <Package PyQt5 (5.12.3)>.
2021-10-15 21:17:13,833 | INFO | Initializing Package {'name': 'PyQtWebEngine', 'version': '5.12.1', 'latest_version': '5.15.4', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2021-10-15 21:17:13,833 | INFO | Fetching package PyQtWebEngine information from DB...
2021-10-15 21:17:13,833 | INFO | Using cached info for package <Package PyQtWebEngine (5.12.1)>.
2021-10-15 21:17:14,429 | INFO | Packages within `pip` /Users/roeravid/opt/anaconda3/bin/pip found: [<Package astroid (2.6.6)>, <Package flake8 (3.9.2)>, <Package idna (2.10)>, <Package jedi (0.17.2)>, <Package jupyter-client (6.1.12)>, <Package parso (0.7.1)>, <Package pycodestyle (2.7.0)>, <Package pycurl (7.43.0.6)>, <Package pyflakes (2.3.1)>, <Package pylint (2.9.6)>, <Package PyQt5 (5.12.3)>, <Package PyQtWebEngine (5.12.1)>]...
2021-10-15 21:17:14,777 | INFO | Initializing Package {'name': 'astroid', 'version': '2.6.6', 'latest_version': '2.8.2', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2021-10-15 21:17:14,777 | INFO | Fetching package astroid information from DB...
2021-10-15 21:17:14,782 | INFO | Using cached info for package <Package astroid (2.6.6)>.
2021-10-15 21:17:14,782 | INFO | Initializing Package {'name': 'flake8', 'version': '3.9.2', 'latest_version': '4.0.1', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2021-10-15 21:17:14,782 | INFO | Fetching package flake8 information from DB...
2021-10-15 21:17:14,783 | INFO | Using cached info for package <Package flake8 (3.9.2)>.
2021-10-15 21:17:14,783 | INFO | Initializing Package {'name': 'idna', 'version': '2.10', 'latest_version': '3.3', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2021-10-15 21:17:14,783 | INFO | Fetching package idna information from DB...
2021-10-15 21:17:14,784 | INFO | Using cached info for package <Package idna (2.10)>.
2021-10-15 21:17:14,786 | INFO | Initializing Package {'name': 'jedi', 'version': '0.17.2', 'latest_version': '0.18.0', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2021-10-15 21:17:14,787 | INFO | Fetching package jedi information from DB...
2021-10-15 21:17:14,788 | INFO | Using cached info for package <Package jedi (0.17.2)>.
2021-10-15 21:17:14,788 | INFO | Initializing Package {'name': 'jupyter-client', 'version': '6.1.12', 'latest_version': '7.0.6', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2021-10-15 21:17:14,789 | INFO | Fetching package jupyter-client information from DB...
2021-10-15 21:17:14,795 | INFO | Using cached info for package <Package jupyter-client (6.1.12)>.
2021-10-15 21:17:14,795 | INFO | Initializing Package {'name': 'parso', 'version': '0.7.1', 'latest_version': '0.8.2', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2021-10-15 21:17:14,796 | INFO | Fetching package parso information from DB...
2021-10-15 21:17:14,796 | INFO | Using cached info for package <Package parso (0.7.1)>.
2021-10-15 21:17:14,797 | INFO | Initializing Package {'name': 'pycodestyle', 'version': '2.7.0', 'latest_version': '2.8.0', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2021-10-15 21:17:14,798 | INFO | Fetching package pycodestyle information from DB...
2021-10-15 21:17:14,798 | INFO | Using cached info for package <Package pycodestyle (2.7.0)>.
2021-10-15 21:17:14,799 | INFO | Initializing Package {'name': 'pycurl', 'version': '7.43.0.6', 'latest_version': '7.44.1', 'latest_filetype': 'sdist'} of type <class 'dict'>...
2021-10-15 21:17:14,799 | INFO | Fetching package pycurl information from DB...
2021-10-15 21:17:14,800 | INFO | Using cached info for package <Package pycurl (7.43.0.6)>.
2021-10-15 21:17:14,800 | INFO | Initializing Package {'name': 'pyflakes', 'version': '2.3.1', 'latest_version': '2.4.0', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2021-10-15 21:17:14,801 | INFO | Fetching package pyflakes information from DB...
2021-10-15 21:17:14,801 | INFO | Using cached info for package <Package pyflakes (2.3.1)>.
2021-10-15 21:17:14,801 | INFO | Initializing Package {'name': 'pylint', 'version': '2.9.6', 'latest_version': '2.11.1', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2021-10-15 21:17:14,801 | INFO | Fetching package pylint information from DB...
2021-10-15 21:17:14,802 | INFO | Using cached info for package <Package pylint (2.9.6)>.
2021-10-15 21:17:14,805 | INFO | Initializing Package {'name': 'PyQt5', 'version': '5.12.3', 'latest_version': '5.15.4', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2021-10-15 21:17:14,805 | INFO | Fetching package PyQt5 information from DB...
2021-10-15 21:17:14,806 | INFO | Using cached info for package <Package PyQt5 (5.12.3)>.
2021-10-15 21:17:14,806 | INFO | Initializing Package {'name': 'PyQtWebEngine', 'version': '5.12.1', 'latest_version': '5.15.4', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2021-10-15 21:17:14,807 | INFO | Fetching package PyQtWebEngine information from DB...
2021-10-15 21:17:14,807 | INFO | Using cached info for package <Package PyQtWebEngine (5.12.1)>.
2021-10-15 21:17:15,068 | INFO | Packages within `pip` /Users/roeravid/opt/anaconda3/bin/pip3 found: [<Package astroid (2.6.6)>, <Package flake8 (3.9.2)>, <Package idna (2.10)>, <Package jedi (0.17.2)>, <Package jupyter-client (6.1.12)>, <Package parso (0.7.1)>, <Package pycodestyle (2.7.0)>, <Package pycurl (7.43.0.6)>, <Package pyflakes (2.3.1)>, <Package pylint (2.9.6)>, <Package PyQt5 (5.12.3)>, <Package PyQtWebEngine (5.12.1)>]...

concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/Users/roeravid/opt/anaconda3/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/Users/roeravid/opt/anaconda3/lib/python3.8/concurrent/futures/process.py", line 198, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/Users/roeravid/opt/anaconda3/lib/python3.8/concurrent/futures/process.py", line 198, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/Users/roeravid/opt/anaconda3/lib/python3.8/site-packages/pipupgrade/commands/helper.py", line 319, in get_registry_from_pip
    _, output, _ = _pip.call("list", user = user, outdated = outdated, \
  File "/Users/roeravid/opt/anaconda3/lib/python3.8/site-packages/pipupgrade/_pip.py", line 76, in call
    output = popen(*params, output = output, raise_err = raise_err)
  File "/Users/roeravid/opt/anaconda3/lib/python3.8/site-packages/bpyutils/util/system.py", line 92, in popen
    raise PopenError(code, command)
bpyutils.exception.PopenError: Command '/usr/local/bin/pip2 list --outdated --format json' returned non-zero exit status 1.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/roeravid/opt/anaconda3/lib/python3.8/site-packages/pipupgrade/commands/__init__.py", line 79, in command
    return _command(**ARGUMENTS)
  File "/Users/roeravid/opt/anaconda3/lib/python3.8/site-packages/pipupgrade/commands/__init__.py", line 240, in _command
    for registry in pool.imap_unordered(
  File "/Users/roeravid/opt/anaconda3/lib/python3.8/concurrent/futures/process.py", line 484, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/Users/roeravid/opt/anaconda3/lib/python3.8/concurrent/futures/_base.py", line 611, in result_iterator
    yield fs.pop().result()
  File "/Users/roeravid/opt/anaconda3/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/Users/roeravid/opt/anaconda3/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
bpyutils.exception.PopenError: Command '/usr/local/bin/pip2 list --outdated --format json' returned non-zero exit status 1.

An error occured while performing the above command. This could be an issue with
"pipupgrade". Kindly post an issue at https://github.com/achillesrasquinha/pipupgrade/issues
```

thanks so much! what an awesome tool. I hope to improve my skills and knowledge so that i too can make the world a better place.

**Comment by chungonion** [comment]
> Could you let me know what `/usr/local/bin/pip2 list --outdated --format json` gives you?

Hi there, I also encountered a similar issue. The `/usr/local/bin/pip2 list --outdated --format json` command gives me the following error message 
```
Traceback (most recent call last):
  File "/usr/local/bin/pip2", line 5, in <module>
    from pip._internal.cli.main import main
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/__init__.py", line 6
    def main(args: Optional[List[str]] = None) -> int:
                 ^
SyntaxError: invalid syntax
```

I am using macOS 12.0.1 . I guess there are some issue with pip2 and is there a way I could exclude pip2 during execution?

Thanks again, your work has benefit me a lot, and I appreciate that =]
