### ISSUE TITLE
Pipupgrade can't upgrade itself

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [achillesrasquinha/pipupgrade#128]
### Description

Getting errors when running pipupgrade

### Console errors

```shell
Source: Installed Distributions (C:\Python310\Scripts\pip.EXE)

Name       Current Version Latest Version Home Page
---------- --------------- -------------- -----------------------------------------------
pipupgrade 1.10.1          1.11.0         https://github.com/achillesrasquinha/pipupgrade

Updating 1 of 1 package: pipupgrade

Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\pipupgrade\commands\__init__.py", line 79, in command
    return _command(**ARGUMENTS)
  File "C:\Python310\lib\site-packages\pipupgrade\commands\__init__.py", line 258, in _command
    update_registry(registry, yes = a.yes, user = a.user, check = a.check,
  File "C:\Python310\lib\site-packages\pipupgrade\commands\helper.py", line 301, in update_registry
    _pip.call("install", package.name,
  File "C:\Python310\lib\site-packages\pipupgrade\_pip.py", line 76, in call
    output = output or quiet
  File "C:\Python310\lib\site-packages\bpyutils\util\system.py", line 92, in popen
    raise PopenError(code, command)
bpyutils.exception.PopenError: Command 'C:\Python310\Scripts\pip.EXE install pipupgrade --no-cache-dir --upgrade' returned non-zero exit status 1.
```
```

**Comment by achillesrasquinha** [comment]
@Unrepentant-Atheist could you show me the logs using `pipupgrade --verbose`?

**Comment by ericdp** [comment]
same on MacOS  (12.1)

`$ pipupgrade
/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/_distutils_hack/__init__.py:35: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Checking...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/pipupgrade", line 5, in <module>
    from pipupgrade.__main__ import main
  File "/usr/local/lib/python3.9/site-packages/pipupgrade/__init__.py", line 23, in <module>
    from pipupgrade.__main__    import main
  File "/usr/local/lib/python3.9/site-packages/pipupgrade/__main__.py", line 5, in <module>
    from   pipupgrade.commands import command as main
  File "/usr/local/lib/python3.9/site-packages/pipupgrade/commands/__init__.py", line 11, in <module>
    from pipupgrade.commands.helper import (
  File "/usr/local/lib/python3.9/site-packages/pipupgrade/commands/helper.py", line 10, in <module>
    from pipupgrade.model         	import Registry
  File "/usr/local/lib/python3.9/site-packages/pipupgrade/model/__init__.py", line 3, in <module>
    from pipupgrade.model.package  import Package
  File "/usr/local/lib/python3.9/site-packages/pipupgrade/model/package.py", line 11, in <module>
    from pipupgrade 	 		import _pip, semver
  File "/usr/local/lib/python3.9/site-packages/pipupgrade/_pip.py", line 7, in <module>
    import pip
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/_distutils_hack/__init__.py", line 83, in find_spec
    return method()
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/_distutils_hack/__init__.py", line 104, in spec_for_pip
    if self.pip_imported_during_build():
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/_distutils_hack/__init__.py", line 115, in pip_imported_during_build
    return any(
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/_distutils_hack/__init__.py", line 116, in <genexpr>
    frame.f_globals['__file__'].endswith('setup.py')
KeyError: '__file__'

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pipupgrade/commands/__init__.py", line 79, in command
    return _command(**ARGUMENTS)
  File "/usr/local/lib/python3.9/site-packages/pipupgrade/commands/__init__.py", line 240, in _command
    for registry in pool.imap_unordered(
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/process.py", line 559, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 608, in result_iterator
    yield fs.pop().result()
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

An error occured while performing the above command. This could be an issue with
"pipupgrade". Kindly post an issue at https://github.com/achillesrasquinha/pipupgrade/issues`


`$ pipupgrade --version
0.2.0

$ python3 --version
Python 3.9.9

$ python --version
Python 2.7.18
`

**Comment by Unrepentant-Atheist** [comment]
@achillesrasquinha  https://pastebin.com/xpEJD2Mp

**Comment by achillesrasquinha** [comment]
Please let me know if this persists in `pipupgrade version 1.12.0

**Comment by Unrepentant-Atheist** [comment]
Works fine now.
