### ISSUE TITLE
Doesn't work on WSL

### ISSUE THREAD

**Issue by lukasz-mitka** [achillesrasquinha/pipupgrade#141]
### Description

Can't even start `pipupgrade` on WSL2 due to missing `tkinter`. Which is kind of weird for CLI tool.
pipupgrade version: `1.12.0`

### Console errors

```shell
> pipupgrade --help
Traceback (most recent call last):
  File "/home/user/.local/bin/pipupgrade", line 5, in <module>
    from pipupgrade.__main__ import main
  File "/home/user/.local/lib/python3.8/site-packages/pipupgrade/__init__.py", line 22, in <module>
    from pipupgrade.config      import PATH
  File "/home/user/.local/lib/python3.8/site-packages/pipupgrade/config.py", line 7, in <module>
    from bpyutils.config      import get_config_path
  File "/home/user/.local/lib/python3.8/site-packages/bpyutils/__init__.py", line 19, in <module>
    from bpyutils import cli
  File "/home/user/.local/lib/python3.8/site-packages/bpyutils/cli/__init__.py", line 5, in <module>
    from bpyutils.cli.parser import get_args
  File "/home/user/.local/lib/python3.8/site-packages/bpyutils/cli/parser.py", line 21, in <module>
    from bpyutils.util.git        import resolve_git_url
  File "/home/user/.local/lib/python3.8/site-packages/bpyutils/util/git.py", line 2, in <module>
    from tkinter import E
ModuleNotFoundError: No module named 'tkinter'
```

**Comment by achillesrasquinha** [comment]
@lukasz-mitka Thanks for reporting. This seems to be a minor error in https://github.com/achillesrasquinha/bpyutils.git
I've fixed and released this on the latest version. 

You might have to update bpyutils to its latest.

```
$ pip install --upgrade bpyutils
```

After which it should work.

**Comment by lukasz-mitka** [comment]
Thank you, I can run it now!
Still getting some errors but they look unrelated. Closing.
