### ISSUE TITLE
ModuleNotFoundError: No module named '_tkinter'

### ISSUE THREAD

**Issue by mrichman** [achillesrasquinha/pipupgrade#142]
### Description

`pipupgrade` fails on macOS Monterey 12.5.1 with Python 3.10.6. Python is installed via `brew install python@3.10`:

```
pipupgrade
Traceback (most recent call last):
  File "/Users/mrkrchm/Library/Python/3.10/bin/pipupgrade", line 5, in <module>
    from pipupgrade.__main__ import main
  File "/Users/mrkrchm/Library/Python/3.10/lib/python/site-packages/pipupgrade/__init__.py", line 22, in <module>
    from pipupgrade.config      import PATH
  File "/Users/mrkrchm/Library/Python/3.10/lib/python/site-packages/pipupgrade/config.py", line 7, in <module>
    from bpyutils.config      import get_config_path
  File "/usr/local/lib/python3.10/site-packages/bpyutils/__init__.py", line 19, in <module>
    from bpyutils import cli
  File "/usr/local/lib/python3.10/site-packages/bpyutils/cli/__init__.py", line 5, in <module>
    from bpyutils.cli.parser import get_args
  File "/usr/local/lib/python3.10/site-packages/bpyutils/cli/parser.py", line 21, in <module>
    from bpyutils.util.git        import resolve_git_url
  File "/usr/local/lib/python3.10/site-packages/bpyutils/util/git.py", line 2, in <module>
    from tkinter import E
  File "/usr/local/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tkinter/__init__.py", line 37, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'
```

**Comment by mrichman** [comment]
Disregard. Solved via `brew install python-tk@3.10`. Tkinter is no longer included with the homebrew formula for Python 3.10.
