### ISSUE TITLE
`bpyutils.exception.PopenError`

### ISSUE THREAD

**Issue by NicolasMICAUX** [achillesrasquinha/pipupgrade#145]
### Description

While doing a simple `pipupgrade` on Ubuntu22.04, python3.10, in normal console (not in a venv). Nothing else running on my PC at the same moment.

### Console errors

```shell
Updating 10 of 83 packages: dbus-python

Traceback (most recent call last):
  File "/home/xxxxxx/.local/lib/python3.10/site-packages/pipupgrade/commands/__init__.py", line 79, in command
    return _command(**ARGUMENTS)
  File "/home/xxxxxx/.local/lib/python3.10/site-packages/pipupgrade/commands/__init__.py", line 258, in _command
    update_registry(registry, yes = a.yes, user = a.user, check = a.check,
  File "/home/xxxxxx/.local/lib/python3.10/site-packages/pipupgrade/commands/helper.py", line 301, in update_registry
    _pip.call("install", package.name,
  File "/home/xxxxxx/.local/lib/python3.10/site-packages/pipupgrade/_pip.py", line 79, in call
    output = popen(*params, output = output, raise_err = raise_err)
  File "/home/xxxxxx/.local/lib/python3.10/site-packages/bpyutils/util/system.py", line 126, in popen
    raise PopenError(code, command)
bpyutils.exception.PopenError: Command '/home/xxxxxx/.local/bin/pip install dbus-python --no-cache-dir --upgrade' returned non-zero exit status 1.

An error occured while performing the above command. This could be an issue with
"pipupgrade". Kindly post an issue at https://github.com/achillesrasquinha/pipupgrade/issues

```
```

**Comment by falko** [comment]
I have the same error and I'm also on Ubuntu 22.04.2 with Python 3.10.6.
@NicolasMICAUX did you find any workaround?

**Comment by NicolasMICAUX** [comment]
Not really. Now I'm just using `--ignore-error` option of pipupgrade. But I don't know what consequences it might have. I've been doing this for 4 months without problems, but might cause some in the future.

**Comment by ricperry** [comment]
Same error: 

```
Do you wish to update 95 packages? [Y/n/q]: y
Updating 1 of 95 packages: breezy

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pipupgrade/commands/__init__.py", line 79, in command
    return _command(**ARGUMENTS)
  File "/usr/local/lib/python3.10/dist-packages/pipupgrade/commands/__init__.py", line 258, in _command
    update_registry(registry, yes = a.yes, user = a.user, check = a.check,
  File "/usr/local/lib/python3.10/dist-packages/pipupgrade/commands/helper.py", line 301, in update_registry
    _pip.call("install", package.name,
  File "/usr/local/lib/python3.10/dist-packages/pipupgrade/_pip.py", line 79, in call
    output = popen(*params, output = output, raise_err = raise_err)
  File "/usr/local/lib/python3.10/dist-packages/bpyutils/util/system.py", line 126, in popen
    raise PopenError(code, command)
bpyutils.exception.PopenError: Command '/usr/bin/pip install breezy --no-cache-dir --upgrade' returned non-zero exit status 1.

An error occured while performing the above command. This could be an issue with
"pipupgrade". Kindly post an issue at https://github.com/achillesrasquinha/pipupgrade/issues

```
