### ISSUE TITLE
ValueError: `pipupgrade -pip`  Failed to initialize project.

### ISSUE THREAD

**Issue by darkstarworks** [achillesrasquinha/pipupgrade#159]
## Description

Upgrading pip [ ⩘](https://github.com/pypa/pip "The Python package installer (GitHub)") $\to$ using $\to$ `pipupgrade`

<table>
<tbody>
<tr>
<th align="right">system</th>
<th align="left">info</th>
</tr>
<tr>
<td align="left">OS Name</td>
<td align="right">Windows 11 Pro</td>
</tr>
<tr>
<td align="left">OS Version</td>
<td align="right">Build 22631</td>
</tr>
<tr>
<th align="right">soft</th>
<th align="left">ware</th>
</tr>
<tr>
<td align="left">$\large{\textsf{{\color{#ffde57}py}{\color{#4584b6}th}{\color{#646464}on~}}}$ $\normalsize{\textsf{{\color{#737373}~-v}}}$</td>
<td align="right">3.12.6</td>
</tr>
<tr>
<td align="left">$\large{\textsf{{\color{#0073b7}pip~}}}$ $\normalsize{\textsf{{\color{#737373}~-v}}}$</td>
<td align="right">24.2</td>
</tr>
</tbody>
</table>

## Command(s) used

```py3
pipupgrade -pip
```

## Console output

```.ps.py
PS C:\Users\darks> pipupgrade -pip
←[0;93mChecking...←[0m
←[0;1m←[0;91mpipupgrade | 2024-09-28 00:59:31,108 | ERROR | ←[0mFailed to initialize project for path C:\Users\darks\ip.

concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Python312\Lib\concurrent\futures\process.py", line 263, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\concurrent\futures\process.py", line 212, in _process_chunk
    return [fn(*args) for args in chunk]
            ^^^^^^^^^
  File "C:\Python312\Lib\site-packages\pipupgrade\model\project.py", line 16, in from_path
    project = Project(path, *args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\pipupgrade\model\project.py", line 24, in __init__
    raise ValueError("Path %s does not exist." % path)
ValueError: Path C:\Users\darks\ip does not exist.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\pipupgrade\commands\__init__.py", line 79, in command
    return _command(**ARGUMENTS)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\pipupgrade\commands\__init__.py", line 207, in _command
    requirements += flatten(map(lambda p: p.requirements, project))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\bpyutils\util\array.py", line 67, in flatten
    flattened = list(chainer(*arr))
                     ^^^^^^^^^^^^^
  File "C:\Python312\Lib\concurrent\futures\process.py", line 642, in _chain_from_iterable_of_lists
    for element in iterable:
                   ^^^^^^^^
  File "C:\Python312\Lib\concurrent\futures\_base.py", line 619, in result_iterator
    yield _result_or_cancel(fs.pop())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\concurrent\futures\_base.py", line 317, in _result_or_cancel
    return fut.result(timeout)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
ValueError: Path C:\Users\darks\ip does not exist.

←[0;91mAn error occured while performing the above command. This could be an issue with
"pipupgrade". Kindly post an issue at https://github.com/achillesrasquinha/pipupgrade/issues←[0m
```

lines: 3, 48

**Comment by Stevenalenga** [comment]
uninstall in install pip again using the command
pip uninstall pipupgrade
pip install pipupgrade

check the directory is correct as well
