### ISSUE TITLE
Issue with new --user flag

### ISSUE THREAD

**Issue by espressobeanies** [achillesrasquinha/pipupgrade#25]
It seems since the addition of the new '--user' flag, pipupgrade seems to break when it goes to upgrade existing packages.

**Comment by achillesrasquinha** [comment]
Hi @espressobeanies, any trace back would be really helpful!

**Comment by espressobeanies** [comment]
Please see below:

```
[user@localhost ~]$ pipupgrade
Checking...

Source: Installed Distributions

Name              Current Version Latest Version Home Page
----------------- --------------- -------------- ------------------------------------------------
cryptography      2.3             2.5            https://github.com/pyca/cryptography
cssselect         0.9.2           1.0.3          https://github.com/scrapy/cssselect
decorator         4.3.0           4.3.2          https://github.com/micheles/decorator
distro            1.3.0           1.4.0          https://github.com/nir0s/distro
Django            2.0.10          2.1.7          https://www.djangoproject.com/
future            0.16.0          0.17.1         https://python-future.org
gpg               1.12.0          1.10.0         https://www.gnupg.org
idna              2.7             2.8            https://github.com/kjd/idna
lxml              4.2.5           4.3.1          http://lxml.de/
MarkupSafe        1.1.0           1.1.1          https://palletsprojects.com/p/markupsafe/
ndg-httpsclient   0.4.0           0.5.1          https://github.com/cedadev/ndg_httpsclient/
ordered-set       2.0.2           3.1            https://github.com/LuminosoInsight/ordered-set
pbr               4.1.1           5.1.2          https://docs.openstack.org/pbr/latest/
pid               2.1.1           2.2.3          https://github.com/trbs/pid/
pip               19.0.2          19.0.3         https://pip.pypa.io/
ply               3.9             3.11           http://www.dabeaz.com/ply/
pyasn1            0.3.7           0.4.5          https://github.com/etingof/pyasn1
pycairo           1.17.1          1.18.0         https://pycairo.readthedocs.io
pycparser         2.14            2.19           https://github.com/eliben/pycparser
pygeoip           0.2.6           0.3.2          https://github.com/appliedsec/pygeoip
Pygments          2.3.0           2.3.1          http://pygments.org/
pykickstart       3.16            3.20           http://fedoraproject.org/wiki/pykickstart
pyparsing         2.2.0           2.3.1          https://github.com/pyparsing/pyparsing/
pyparted          3.11.0          3.10.7         https://fedorahosted.org/pyparted/
pyRFC3339         1.0             1.1            https://github.com/kurtraschke/pyRFC3339
python-dateutil   2.7.5           2.8.0          https://dateutil.readthedocs.io
pytz              2018.5          2018.9         http://pythonhosted.org/pytz
requests          2.20.0          2.21.0         http://python-requests.org
requests-toolbelt 0.8.0           0.9.1          https://toolbelt.readthedocs.org
rpm               4.14.2.1        0.0.2          https://github.com/ncoghlan/pypi-rpm
six               1.11.0          1.12.0         https://github.com/benjaminp/six
slip              0.6.4           20171205       https://github.com/bicv/SLIP
virtualenv        16.1.0          16.4.1         https://virtualenv.pypa.io/
wheel             0.33.0          0.33.1         https://github.com/pypa/wheel
zope.component    4.3.0           4.5            https://github.com/zopefoundation/zope.component
zope.event        4.2.0           4.4            http://github.com/zopefoundation/zope.event
zope.interface    4.5.0           4.6.0          https://github.com/zopefoundation/zope.interface

Do you wish to update 35 packages? [Y/n]: y
Updating 1 of 35 packages: cryptography
Command "/usr/bin/python3 /usr/local/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-q_yvqbg7/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools>=18.5 wheel "cffi>=1.8,!=1.11.3; python_implementation != 'PyPy'"" failed with error code 1 in None
You are using pip version 19.0.2, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Traceback (most recent call last):
  File "/usr/local/bin/pipupgrade", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/pipupgrade/cli/__init__.py", line 14, in wrapper
    return fn(**params)
  File "/usr/local/lib/python3.7/site-packages/pipupgrade/commands/__init__.py", line 204, in command
    _pip.install(package.name, pip_exec = pip_path, user = user, quiet = not verbose, no_cache_dir = True, upgrade = True)
  File "/usr/local/lib/python3.7/site-packages/pipupgrade/_pip.py", line 63, in install
    popen(*params)
  File "/usr/local/lib/python3.7/site-packages/pipupgrade/util/system.py", line 59, in popen
    raise sp.CalledProcessError(code, command)
subprocess.CalledProcessError: Command '/usr/local/bin/pip install --quiet --no-cache-dir --upgrade cryptography' returned non-zero exit status 1.
```

**Comment by espressobeanies** [comment]
This issue seems to go away if you manually upgrade PIP to 19.03 and install the following dependencies:
libffi-devel, pcre2-devel, openssl-devel, krb5-devel
Also, the 'cffi' package needs to be installed and fixed for everything else to work. In the end it's about tracebacking the python error messages, not looking at a `--user` option.
