### ISSUE TITLE
Crashes on invocation

### ISSUE THREAD

**Issue by dschuessler** [achillesrasquinha/pipupgrade#27]
```
$ pipupgrade
Checking...
Traceback (most recent call last):
  File "/usr/local/bin/pipupgrade", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/pipupgrade/cli/__init__.py", line 14, in wrapper
    return fn(**params)
  File "/usr/local/lib/python3.7/site-packages/pipupgrade/commands/__init__.py", line 162, in command
    format = "json", pip_exec = pip_)
  File "/usr/local/lib/python3.7/site-packages/pipupgrade/_pip.py", line 65, in call
    return popen(*params, output = True)
  File "/usr/local/lib/python3.7/site-packages/pipupgrade/util/system.py", line 69, in popen
    raise sp.CalledProcessError(code, command)
subprocess.CalledProcessError: Command 'None list --outdated --format json' returned non-zero exit status 127.
```

Also happens with no flags and `--latest --yes`

macOS 10.14.4
Python 3.7.3
pip 19.0.3

**Comment by micgro42** [comment]
I have that problem on Ubuntu as well:
```
$pipupgrade --latest --interactive
Checking...
Traceback (most recent call last):
  File "/home/migr/.local/bin//pipupgrade", line 11, in <module>
    sys.exit(main())
  File "/home/migr/.local/lib/python2.7/site-packages/pipupgrade/cli/__init__.py", line 14, in wrapper
    return fn(**params)
  File "/home/migr/.local/lib/python2.7/site-packages/pipupgrade/commands/__init__.py", line 162, in command
    format = "json", pip_exec = pip_)
  File "/home/migr/.local/lib/python2.7/site-packages/pipupgrade/_pip.py", line 65, in call
    return popen(*params, output = True)
  File "/home/migr/.local/lib/python2.7/site-packages/pipupgrade/util/system.py", line 69, in popen
    raise sp.CalledProcessError(code, command)
subprocess.CalledProcessError: Command 'None list --outdated --format json' returned non-zero exit status 127
```
Ubuntu 4.15.0-43-generic
Python 2.7.15rc1
pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)

**Comment by binarykitchen** [comment]
Same problem here. Happened right after I switched from python v3.7.2 to v3.7.3 using pyenv.

**Comment by achillesrasquinha** [comment]
Hi everyone, thank you for tracking this issue down. I'll respond at the earliest!

**Comment by achillesrasquinha** [comment]
`pipupgrade` version?

**Comment by dschuessler** [comment]
1.5.0

**Comment by achillesrasquinha** [comment]
Can you try adding a pip-path as your option and does that work?

```
$ pipupgrade --pip-path pip [OPTIONS]
```

**Comment by dschuessler** [comment]
I think so:

```
pipupgrade --pip-path pip
Checking...

Source: Installed Distributions (/usr/local/opt/python/libexec/bin/pip)

Name              Current Version Latest Version Home Page                                                               
----------------- --------------- -------------- ------------------------------------------------------------------------
astroid           2.1.0           2.2.5          https://github.com/PyCQA/astroid                                        
[...]                                      
wrapt             1.10.11         1.11.1         https://github.com/GrahamDumpleton/wrapt                                

Do you wish to update 20 packages? [Y/n/q]: 
```

**Comment by achillesrasquinha** [comment]
The expected behaviour is pipupgrade detects pip executables for you and attempts to upgrade all packages within their corresponding environments. This behaviour can be overridden using the `--pip-path` option. However, I'm guessing that `pipupgrade` wasn't able to detect a valid `pip` executable for you. Hence, `None list --outdated --format json`.

I'll take a look into it and dispatch a fix as soon as possible! :)

**Comment by achillesrasquinha** [comment]
@slw07g recommended this earlier at #13

**Comment by achillesrasquinha** [comment]
This has been fixed. Pending for release. Please use `pipupgrade --self` and try again.

**Comment by achillesrasquinha** [comment]
Released with 1.5.1

**Comment by achillesrasquinha** [comment]
`$ pipupgrade --version`?

**Comment by dschuessler** [comment]
```
$ pipupgrade --version
1.5.0
```

**Comment by achillesrasquinha** [comment]
Can you try it now? `pipupgrade --self`

**Comment by dschuessler** [comment]
It’s still the same.

**Comment by achillesrasquinha** [comment]
@dschuessler 

Could you update it manually otherwise

```
$ pip install --upgrade --no-cache pipupgrade
```

**Comment by dschuessler** [comment]
It is working now. 👍

**Comment by achillesrasquinha** [comment]
Great! Please repopen if persits.
