### ISSUE TITLE
pipupgrade fails unless `requests` is installed globally.

### ISSUE THREAD

**Issue by ryanpcmcquen** [achillesrasquinha/pipupgrade#29]
```
Checking...
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pipupgrade/request/__init__.py", line 20, in get
    import requests as req
ModuleNotFoundError: No module named 'requests'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pipupgrade", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/pipupgrade/cli/__init__.py", line 14, in wrapper
    return fn(**params)
  File "/usr/local/lib/python3.7/site-packages/pipupgrade/commands/__init__.py", line 177, in command
    package 	 	  = Package(package)
  File "/usr/local/lib/python3.7/site-packages/pipupgrade/model/package.py", line 32, in __init__
    _pypi_info = _get_pypi_info(self.name, raise_err = False) or { }
  File "/usr/local/lib/python3.7/site-packages/pipupgrade/model/package.py", line 6, in _get_pypi_info
    res  = req.get(url)
  File "/usr/local/lib/python3.7/site-packages/pipupgrade/request/__init__.py", line 27, in get
    http_response    = urlopen(url)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 516, in open
    req.timeout = timeout
AttributeError: 'NoneType' object has no attribute 'timeout'
```

This should be mentioned on the README, or, even better, pulled in on a fresh install.

**Comment by achillesrasquinha** [comment]
@ryanpcmcquen, pipupgrade uses the native urllib, in case request isn't found. This seems to be more of an issue of raising a `ModuleNotFoundError` over `ImportError`. Will dispatch a fix soon.

**Comment by ryanpcmcquen** [comment]
Good to know, it wouldn't run for me though until I installed `requests`.

**Comment by binarykitchen** [comment]
It's been a while. Any news on this?

**Comment by achillesrasquinha** [comment]
Has been fixed, pending for release!
