### ISSUE TITLE
os.EX_OK and os.EX_NOINPUT constants are not available on Windows

### ISSUE THREAD

**Issue by PalmtopTiger** [achillesrasquinha/pipupgrade#31]
```
$ pipupgrade.exe
Checking...

Source: Installed Distributions (C:\Python27\Scripts\pip.exe)

Name      Current Version Latest Version Home Page
--------- --------------- -------------- --------------------------
mercurial 5.0             5.0.1          https://mercurial-scm.org/

Do you wish to update 1 package? [Y/n/q]: q
Traceback (most recent call last):
  File "c:\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python37\Scripts\pipupgrade.exe\__main__.py", line 9, in <module>
  File "c:\python37\lib\site-packages\pipupgrade\cli\__init__.py", line 14, in wrapper
    return fn(**params)
  File "c:\python37\lib\site-packages\pipupgrade\commands\__init__.py", line 237, in command
    if npackages and (yes or interactive or cli.confirm(query, quit_ = True)):
  File "c:\python37\lib\site-packages\pipupgrade\cli\util.py", line 29, in confirm
    sys.exit(os.EX_OK)
AttributeError: module 'os' has no attribute 'EX_OK'
```

Docs: https://docs.python.org/3/library/os.html#os.EX_OK

**Comment by achillesrasquinha** [comment]
Fixed. Pending for release!

**Comment by PalmtopTiger** [comment]
Thank you. os.EX_NOINPUT is also [unavailable](https://docs.python.org/3/library/os.html#os.EX_NOINPUT) on Windows. Used [here](https://github.com/achillesrasquinha/pipupgrade/blob/2f244c9beb44b67ddf69a9cafcedc282ae8c1357/src/pipupgrade/commands/__init__.py#L157) and [here](https://github.com/achillesrasquinha/pipupgrade/blob/2f244c9beb44b67ddf69a9cafcedc282ae8c1357/src/pipupgrade/commands/__init__.py#L168).
