### ISSUE TITLE
Windows subsystem: Ubuntu error when "pipupgrade --latest --yes"

### ISSUE THREAD

**Issue by caniko2** [achillesrasquinha/pipupgrade#34]
Printout:
```
Checking...
Traceback (most recent call last):
  File "/home/can/.local/bin/pipupgrade", line 11, in <module>
    sys.exit(main())
  File "/home/can/.local/lib/python3.6/site-packages/pipupgrade/cli/__init__.py", line 14, in wrapper
    return fn(**params)
  File "/home/can/.local/lib/python3.6/site-packages/pipupgrade/commands/__init__.py", line 178, in command
    format = "json", pip_exec = pip_)
  File "/home/can/.local/lib/python3.6/site-packages/pipupgrade/_pip.py", line 69, in call
    return popen(*params, output = True)
  File "/home/can/.local/lib/python3.6/site-packages/pipupgrade/util/system.py", line 70, in popen
    raise sp.CalledProcessError(code, command)
subprocess.CalledProcessError: Command '/usr/bin/pip3 list --outdated --format json' returned non-zero exit status 2.
```

**Comment by caniko2** [comment]
There was

**Comment by caniko2** [comment]
I think the issue is that there is nothing to update. Maybe make an exception handler for this?

**Comment by achillesrasquinha** [comment]
`pip` version?

**Comment by cocoonkid** [comment]
I have a similar issue:

pipupgrade
Checking...
Traceback (most recent call last):
File "/Users/cocoonkid/.pyenv/versions/3.7.1/bin/pipupgrade", line 10, in 
sys.exit(main())
File "/Users/cocoonkid/.pyenv/versions/3.7.1/lib/python3.7/site-packages/pipupgrade/cli/init.py", line 14, in wrapper
return fn(**params)
File "/Users/cocoonkid/.pyenv/versions/3.7.1/lib/python3.7/site-packages/pipupgrade/commands/init.py", line 178, in command
format = "json", pip_exec = pip_)
File "/Users/cocoonkid/.pyenv/versions/3.7.1/lib/python3.7/site-packages/pipupgrade/_pip.py", line 69, in call
return popen(*params, output = True)
File "/Users/cocoonkid/.pyenv/versions/3.7.1/lib/python3.7/site-packages/pipupgrade/util/system.py", line 70, in popen
raise sp.CalledProcessError(code, command)
subprocess.CalledProcessError: Command '/Users/cocoonkid/.pyenv/shims/pip2 list --outdated --format json' returned non-zero exit status 127.

The command should run pip3 list --outdated --format json

Thank you for this great tool!

**Comment by achillesrasquinha** [comment]
Hi guys, does this issue still exist with latest version 1.6.5?

**Comment by tibor** [comment]
Got a similar issue with the newest pipupgrade:

```

pipupgrade 
Checking...
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/usr/local/lib/python3.6/dist-packages/pipupgrade/commands/helper.py", line 146, in get_registry_from_pip
    format = "json", pip_exec = pip_path, output = True)
  File "/usr/local/lib/python3.6/dist-packages/pipupgrade/_pip.py", line 74, in call
    output = popen(*params, output = output, raise_err = raise_err)
  File "/usr/local/lib/python3.6/dist-packages/pipupgrade/util/system.py", line 78, in popen
    raise PopenError(code, command)
pipupgrade.exception.PopenError: Command '/usr/bin/pip3 list --outdated --format json' returned non-zero exit status 2.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/pipupgrade", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/pipupgrade/cli/__init__.py", line 15, in wrapper
    return fn(**params)
  File "/usr/local/lib/python3.6/dist-packages/pipupgrade/commands/__init__.py", line 153, in command
    pip_path
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
pipupgrade.exception.PopenError: Command '/usr/bin/pip3 list --outdated --format json' returned non-zero exit status 2.

```

**Comment by achillesrasquinha** [comment]
@tibor pip version?

**Comment by tibor** [comment]
@achillesrasquinha pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)

**Comment by achillesrasquinha** [comment]
Hmm, does `pip list --format json` work for you?

**Comment by achillesrasquinha** [comment]
I'm guessing `pip list --format json` wouldn't exist for your pip version.

**Comment by tibor** [comment]
`pip list --format json` doesn’t work, but `pip3 list --format json` works as expected

**Comment by achillesrasquinha** [comment]
Hmm,

Could you provide me the output for `pip --version` and `pip3 --version`?

**Comment by tibor** [comment]
```pip --version
-bash: pip: command not found
```

```pip3 --version
pip 19.3.1 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)
```

**Comment by tibor** [comment]
Fixed this indeed by upgrading pip3 with
`sudo pip3 install --upgrade pip`

https://github.com/pypa/pip/issues/5429

**Comment by achillesrasquinha** [comment]
@tibor Nice, You can also pass `--pip-path` using `pipupgrade` as follows

```
$ pipupgrade --pip-path pip3
```

**Comment by achillesrasquinha** [comment]
Closing this.
