### ISSUE TITLE
Cannot support spaces in path

### ISSUE THREAD

**Issue by Xarkam** [achillesrasquinha/pipupgrade#35]
Hello, I see, pipupgrade cannot run in windows if the path contain spaces:
```bash
PS C:\Windows\System32> pipupgrade --latest --yes
[0;93mChecking...[0m
Traceback (most recent call last):
  File "c:\program files\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python37\Scripts\pipupgrade.exe\__main__.py", line 9, in <module>
  File "c:\program files\python37\lib\site-packages\pipupgrade\cli\__init__.py", line 14, in wrapper
    return fn(**params)
  File "c:\program files\python37\lib\site-packages\pipupgrade\commands\__init__.py", line 178, in command
    format = "json", pip_exec = pip_)
  File "c:\program files\python37\lib\site-packages\pipupgrade\_pip.py", line 69, in call
    return popen(*params, output = True)
  File "c:\program files\python37\lib\site-packages\pipupgrade\util\system.py", line 70, in popen
    raise sp.CalledProcessError(code, command)
subprocess.CalledProcessError: Command 'C:\Program Files\Python37\Scripts\pip.exe list --outdated --format json' returned non-zero exit status 1.
```
the command `pip.exe list` run perfect:
```bash
PS C:\Windows\System32> pip.exe list --outdated --format json
[{"name": "port-for", "version": "0.3.1", "latest_version": "0.4", "latest_filetype": "wheel"}, {"name": "setuptools", "version": "40.8.0", "latest_version": "41.0.1", "latest_filetype": "wheel"}]
```

Python version: 3.7.4 x64
Pip version: 19.2.1
pipupgrade version: latest.
![image](https://user-images.githubusercontent.com/331816/62517419-a8fe8a80-b827-11e9-97c2-09199108b108.png)

**Comment by arian-f** [comment]
the bug is still present, although the traceback is different now:

```
2021-12-07 11:19:51,351 | INFO | Executing command: C:\Program Files\Python39\Scripts\pip.EXE list --outdated --format json

concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\concurrent\futures\process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "C:\Program Files\Python39\lib\concurrent\futures\process.py", line 202, in _process_chunk
    return [fn(*args) for args in chunk]
  File "C:\Program Files\Python39\lib\concurrent\futures\process.py", line 202, in <listcomp>
    return [fn(*args) for args in chunk]
  File "C:\Users\user\backup\src\pipupgrade\src\pipupgrade\commands\helper.py", line 319, in get_registry_from_pip
    _, output, _ = _pip.call("list", user = user, outdated = outdated, \
  File "C:\Users\user\backup\src\pipupgrade\src\pipupgrade\_pip.py", line 78, in call
    output = popen(*params, output = output, raise_err = raise_err)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\bpyutils\util\system.py", line 92, in popen
    raise PopenError(code, command)
bpyutils.exception.PopenError: Command 'C:\Program Files\Python39\Scripts\pip.EXE list --outdated --format json' returned non-zero exit status 1.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\backup\src\pipupgrade\src\pipupgrade\commands\__init__.py", line 79, in command
    return _command(**ARGUMENTS)
  File "C:\Users\user\backup\src\pipupgrade\src\pipupgrade\commands\__init__.py", line 240, in _command
    for registry in pool.imap_unordered(
  File "C:\Program Files\Python39\lib\concurrent\futures\process.py", line 559, in _chain_from_iterable_of_lists
    for element in iterable:
  File "C:\Program Files\Python39\lib\concurrent\futures\_base.py", line 608, in result_iterator
    yield fs.pop().result()
  File "C:\Program Files\Python39\lib\concurrent\futures\_base.py", line 445, in result
    return self.__get_result()
  File "C:\Program Files\Python39\lib\concurrent\futures\_base.py", line 390, in __get_result
    raise self._exception
bpyutils.exception.PopenError: Command 'C:\Program Files\Python39\Scripts\pip.EXE list --outdated --format json' returned non-zero exit status 1.

An error occured while performing the above command. This could be an issue with
"pipupgrade". Kindly post an issue at https://github.com/achillesrasquinha/pipupgrade/issues
```

the issue is now in bpyutils, where in `bpyutils.util.system.popen`:

```
    command     = " ".join([str(arg) for arg in args])
```
it's converted to single string for the shell without escaping spaces in the path
