### ISSUE TITLE
Cannot upgrade packages on Mac OS 10.14.x

### ISSUE THREAD

**Issue by ryanpcmcquen** [achillesrasquinha/pipupgrade#40]
```λ pipupgrade --interactive
Checking...
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/usr/local/lib/python3.7/site-packages/pipupgrade/commands/helper.py", line 109, in get_registry_from_pip
    installed = True, sync = sync)
  File "/usr/local/lib/python3.7/site-packages/pipupgrade/model/registry.py", line 13, in __init__
    for p in packages
  File "/usr/local/lib/python3.7/site-packages/pipupgrade/model/registry.py", line 13, in <listcomp>
    for p in packages
  File "/usr/local/lib/python3.7/site-packages/pipupgrade/model/package.py", line 87, in __init__
    self.latest_version = res["latest_version"]
TypeError: list indices must be integers or slices, not str
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/pipupgrade", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/pipupgrade/cli/__init__.py", line 14, in wrapper
    return fn(**params)
  File "/usr/local/lib/python3.7/site-packages/pipupgrade/commands/__init__.py", line 118, in command
    pip_path
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
TypeError: list indices must be integers or slices, not str```

I've tried removing the `pip` cache (`rm -rf ~/Library/Caches/pip`).

**Comment by JayRizzo** [comment]
# Working Theory 
To Iterate as a short version of my items listed below: 

### Tried:
- Last 3 versions of pipupgrade
- ignoring python2 when viewing pipupgrade
- following down the error

This is an issue for the last 3 versions of pipupgrade for `mac OSX Mojave 10.14.6`.

Even when I ignore pip2 upgrades (on all of last 3 `pipupgrade` versions) I still get an `--user` error and some upgrades return a `Non-zero exit code` due to permissions.

Lastly, when I followed down the error it looks as though there is an issue regarding the `self._map_async` from the file `python3.7/multiprocessing/pool.py` as it is returning the wrong values that are Strings of `'None'` instead of there intended values from before. 

So, I am under the impression the direct cause was something from a previous PR #17
I believe that changed [`src/pipupgrade/_pip.py`](https://github.com/achillesrasquinha/pipupgrade/pull/17/files#diff-d605368b5837d375dfd24731f4f19623) in which that broke for Mac users?

But that is my theory, and here is my detail...

_(sorry for all the detail, just hope it helps someone)_

# FULL DETAIL BELOW
## My Attempted Workaround

1. Install a previous working version:
I tried 1.4.0, 1.5.0, 1.5.1
```
pip install pipupgrade==1.5.0
pip3 install pipupgrade==1.5.0
```
1. Then run with interactive and don't update `pipupgrade`
```
pipupgrade --interactive --verbose
# ignore any and all of python2 to jump straight to python3 updates  
# then lastly ignore pip2 locale updates as well.
```
## Failed
I got these issues for both python2 & python3 using `pipupgrade`

- Still this **failed** due to issues with not passing the `--user` option

Example:
```
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/site-packages/PyAutoGUI-0.9.47.dist-info/RECORD'
Consider using the `--user` option or check the permissions.
```

# reinstalling it

I tired uninstalling both versions 

```
pip uninstall pipupgrade
pip3 uninstall pipupgrade
```

and just installing pip3 version
`pip3 install pipupgrade`

Still an error

# Tracing Error

So I tracked this down and the files that are passing values to the multiprocessing/pool.py are having an issue because it is passing sting values of 'None' to the function.

```
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 575, in get
    raise self._value
TypeError: list indices must be integers, not str
```

I modified the above file to see the output:

```
    def get(self, timeout=None):
        print("Self         ######## %s" % type(self._value))
        print("Self _success ######## %s" % self._success.__str__())
        print("Self _value ######## %s" % self._value.__str__())
        self.wait(timeout)
        if not self._ready:
            raise TimeoutError
        if self._success:
            return self._value
        else:
            raise self._value
```

and i got was:
```

Self         ######## <type 'list'>
Self _success ######## True
Self _value ######## [None, None, None]

```





## Full Error:


```
pipupgrade --verbose
Checking...
2019-10-19 14:36:21,950 | INFO | Arguments Passed: {'verbose': True, 'pip_path': None, 'github_username': None, 'yes': False, 'check': False, 'target_branch': 'master', 'requirements': None, 'git_username': None, 'self': False, 'git_email': None, 'no_color': False, 'no_included_requirements': False, 'github_reponame': None, 'jobs': 8, 'github_access_token': None, 'user': False, 'pull_request': False, 'project': None, 'no_cache': False, 'pipfile': None, 'interactive': False, 'latest': False}
2019-10-19 14:36:21,950 | INFO | `pip` executables found: ['/usr/local/bin/pip', '/usr/local/bin/pip3', '/usr/local/bin/pip2']
2019-10-19 14:36:21,950 | INFO | Using 8 jobs...
2019-10-19 14:36:31,658 | INFO | Initializing Package {u'latest_filetype': u'wheel', u'version': u'0.24.0', u'name': u'asn1crypto', u'latest_version': u'1.2.0'} of type <type 'dict'>...
2019-10-19 14:36:31,658 | INFO | Establishing a DataBase connection...
2019-10-19 14:36:31,659 | INFO | Bootstrapping DataBase...
2019-10-19 14:36:31,660 | INFO | Using cached info for package <Package asn1crypto (0.24.0)>.
2019-10-19 14:36:31,660 | INFO | Initializing Package {u'latest_filetype': u'wheel', u'version': u'2018.8.13', u'name': u'certifi', u'latest_version': u'2019.9.11'} of type <type 'dict'>...
2019-10-19 14:36:31,660 | INFO | Using cached info for package <Package certifi (2018.8.13)>.
2019-10-19 14:36:31,660 | INFO | Initializing Package {u'latest_filetype': u'wheel', u'version': u'6.3.1', u'name': u'elasticsearch', u'latest_version': u'7.0.5'} of type <type 'dict'>...
2019-10-19 14:36:31,661 | INFO | Using cached info for package <Package elasticsearch (6.3.1)>.
2019-10-19 14:36:31,661 | INFO | Initializing Package {u'latest_filetype': u'sdist', u'version': u'0.0.4', u'name': u'MouseInfo', u'latest_version': u'0.1.2'} of type <type 'dict'>...
2019-10-19 14:36:31,661 | INFO | Using cached info for package <Package MouseInfo (0.0.4)>.
Traceback (most recent call last):
  File "/usr/local/bin/pipupgrade", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/pipupgrade/cli/__init__.py", line 14, in wrapper
    return fn(**params)
  File "/usr/local/lib/python2.7/site-packages/pipupgrade/commands/__init__.py", line 117, in command
    pip_path
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
TypeError: list indices must be integers, not str
```

## Calling it directly from `python3 -m`

```
$ python3 -m pipupgrade
/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py:125: RuntimeWarning: 'pipupgrade.__main__' found in sys.modules after import of package 'pipupgrade', but prior to execution of 'pipupgrade.__main__'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
Checking...
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/usr/local/lib/python3.7/site-packages/pipupgrade/commands/helper.py", line 109, in get_registry_from_pip
    installed = True, sync = sync)
  File "/usr/local/lib/python3.7/site-packages/pipupgrade/model/registry.py", line 13, in __init__
    for p in packages
  File "/usr/local/lib/python3.7/site-packages/pipupgrade/model/registry.py", line 13, in <listcomp>
    for p in packages
  File "/usr/local/lib/python3.7/site-packages/pipupgrade/model/package.py", line 87, in __init__
    self.latest_version = res["latest_version"]
TypeError: list indices must be integers or slices, not str
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/site-packages/pipupgrade/__main__.py", line 8, in <module>
    main()
  File "/usr/local/lib/python3.7/site-packages/pipupgrade/cli/__init__.py", line 14, in wrapper
    return fn(**params)
  File "/usr/local/lib/python3.7/site-packages/pipupgrade/commands/__init__.py", line 118, in command
    pip_path
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
TypeError: list indices must be integers or slices, not str

```

**Comment by atanasj** [comment]
I am getting this error too: 

```
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G103
Python 3.7.5
Python 2.7.17
pipupgrade 1.5.2
```
Looking forward to a resolution.

**Comment by uhlhosting** [comment]
```
Source: Installed Distributions (/usr/local/bin/pip)

Name                                   Current Version Latest Version Home Page                                      
-------------------------------------- --------------- -------------- -----------------------------------------------
altgraph                               0.10.2          0.16.1         https://altgraph.readthedocs.io                
ansible                                2.7.12          2.9.2          https://ansible.com/                           
asn1crypto                             0.24.0          1.2.0          https://github.com/wbond/asn1crypto            
certifi                                2019.9.11       2019.11.28     https://certifi.io/                            
cffi                                   1.12.2          1.13.2         http://cffi.readthedocs.org                    
cryptography                           2.6.1           2.8            https://github.com/pyca/cryptography           
future                                 0.17.1          0.18.2         https://python-future.org                      
importlib-metadata                     0.23            1.3.0          http://importlib-metadata.readthedocs.io/      
ipaddress                              1.0.22          1.0.23         https://github.com/phihag/ipaddress            
macholib                               1.5.1           1.11           http://bitbucket.org/ronaldoussoren/macholib   
matplotlib                             1.3.1           2.2.4          https://matplotlib.org                         
modulegraph                            0.10.4          0.17           http://bitbucket.org/ronaldoussoren/modulegraph
numpy                                  1.8.0rc1        1.16.5         https://www.numpy.org                          
py2app                                 0.7.3           0.19           http://bitbucket.org/ronaldoussoren/py2app     
pyobjc-core                            2.5.1           5.3            https://bitbucket.org/ronaldoussoren/pyobjc    
pyobjc-framework-Accounts              2.5.1           5.3            https://bitbucket.org/ronaldoussoren/pyobjc    
pyobjc-framework-AddressBook           2.5.1           5.3            https://bitbucket.org/ronaldoussoren/pyobjc    
pyobjc-framework-AppleScriptKit        2.5.1           5.3            https://bitbucket.org/ronaldoussoren/pyobjc    
pyobjc-framework-AppleScriptObjC       2.5.1           5.3            https://bitbucket.org/ronaldoussoren/pyobjc    
pyobjc-framework-Automator             2.5.1           5.3            https://bitbucket.org/ronaldoussoren/pyobjc    
pyobjc-framework-CFNetwork             2.5.1           5.3            https://bitbucket.org/ronaldoussoren/pyobjc    
pyobjc-framework-Cocoa                 2.5.1           5.3            https://bitbucket.org/ronaldoussoren/pyobjc    
pyobjc-framework-Collaboration         2.5.1           5.3            https://bitbucket.org/ronaldoussoren/pyobjc    
pyobjc-framework-CoreData              2.5.1           5.3            https://bitbucket.org/ronaldoussoren/pyobjc    
pyobjc-framework-CoreLocation          2.5.1           5.3            https://bitbucket.org/ronaldoussoren/pyobjc    
pyobjc-framework-CoreText              2.5.1           5.3            https://bitbucket.org/ronaldoussoren/pyobjc    
pyobjc-framework-DictionaryServices    2.5.1           5.3            https://bitbucket.org/ronaldoussoren/pyobjc    
pyobjc-framework-EventKit              2.5.1           5.3            https://bitbucket.org/ronaldoussoren/pyobjc    
pyobjc-framework-ExceptionHandling     2.5.1           5.3            https://bitbucket.org/ronaldoussoren/pyobjc    
pyobjc-framework-FSEvents              2.5.1           5.3            https://bitbucket.org/ronaldoussoren/pyobjc    
pyobjc-framework-InputMethodKit        2.5.1           5.3            https://bitbucket.org/ronaldoussoren/pyobjc    
pyobjc-framework-InstallerPlugins      2.5.1           5.3            https://bitbucket.org/ronaldoussoren/pyobjc    
pyobjc-framework-InstantMessage        2.5.1           5.3            https://bitbucket.org/ronaldoussoren/pyobjc    
pyobjc-framework-LatentSemanticMapping 2.5.1           5.3            https://bitbucket.org/ronaldoussoren/pyobjc    
pyobjc-framework-LaunchServices        2.5.1           5.3            https://bitbucket.org/ronaldoussoren/pyobjc    
pyobjc-framework-Message               2.5.1           5.3            https://bitbucket.org/ronaldoussoren/pyobjc    
pyobjc-framework-OpenDirectory         2.5.1           5.3            https://bitbucket.org/ronaldoussoren/pyobjc    
pyobjc-framework-PreferencePanes       2.5.1           5.3            https://bitbucket.org/ronaldoussoren/pyobjc    
pyobjc-framework-PubSub                2.5.1           5.3            https://bitbucket.org/ronaldoussoren/pyobjc    
pyobjc-framework-QTKit                 2.5.1           5.3            https://bitbucket.org/ronaldoussoren/pyobjc    
pyobjc-framework-Quartz                2.5.1           5.3            https://bitbucket.org/ronaldoussoren/pyobjc    
pyobjc-framework-ScreenSaver           2.5.1           5.3            https://bitbucket.org/ronaldoussoren/pyobjc    
pyobjc-framework-ScriptingBridge       2.5.1           5.3            https://bitbucket.org/ronaldoussoren/pyobjc    
pyobjc-framework-SearchKit             2.5.1           5.3            https://bitbucket.org/ronaldoussoren/pyobjc    
pyobjc-framework-ServiceManagement     2.5.1           5.3            https://bitbucket.org/ronaldoussoren/pyobjc    
pyobjc-framework-Social                2.5.1           5.3            https://bitbucket.org/ronaldoussoren/pyobjc    
pyobjc-framework-SyncServices          2.5.1           5.3            https://bitbucket.org/ronaldoussoren/pyobjc    
pyobjc-framework-SystemConfiguration   2.5.1           5.3            https://bitbucket.org/ronaldoussoren/pyobjc    
pyobjc-framework-WebKit                2.5.1           5.3            https://bitbucket.org/ronaldoussoren/pyobjc    
pyOpenSSL                              19.0.0          19.1.0         https://pyopenssl.org/                         
scipy                                  0.13.0b1        1.2.2          https://www.scipy.org                          
setuptools                             41.0.1          42.0.2         https://github.com/pypa/setuptools             
six                                    1.12.0          1.13.0         https://github.com/benjaminp/six               
virtualenv                             16.7.8          16.7.9         https://virtualenv.pypa.io/                    
wheel                                  0.33.1          0.33.6         https://github.com/pypa/wheel                  
xattr                                  0.6.4           0.9.7          http://github.com/xattr/xattr                  

Updating 1 of 56 packages: altgraph
Updating 2 of 15 packages: cliff
Updating 3 of 15 packages: cmd2
Updating 4 of 15 packages: importlib-metadata
Updating 5 of 15 packages: kolla-ansible
Updating 6 of 15 packages: more-itertools
Updating 7 of 15 packages: openstacksdk
Updating 8 of 15 packages: osc-lib
Updating 9 of 15 packages: oslo.log
Updating 10 of 15 packages: oslo.utils
Updating 11 of 15 packages: python-troveclient
Updating 12 of 15 packages: PyYAML
Updating 13 of 15 packages: semantic-version
Updating 14 of 15 packages: setuptools
Updating 15 of 15 packages: virtualenv
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/usr/local/lib/python3.7/site-packages/pipupgrade/commands/helper.py", line 196, in update_registry
    _pip.call("install", package.name, pip_exec = package.source, user = user, quiet = not verbose, no_cache_dir = True, upgrade = True)
  File "/usr/local/lib/python3.7/site-packages/pipupgrade/_pip.py", line 73, in call
    return popen(*params, output = output)
  File "/usr/local/lib/python3.7/site-packages/pipupgrade/util/system.py", line 70, in popen
    raise sp.CalledProcessError(code, command)
subprocess.CalledProcessError: Command '/usr/local/bin/pip install altgraph --no-cache-dir --upgrade' returned non-zero exit status 1.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/pipupgrade", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/pipupgrade/cli/__init__.py", line 14, in wrapper
    return fn(**params)
  File "/usr/local/lib/python3.7/site-packages/pipupgrade/commands/__init__.py", line 131, in command
    registries
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
subprocess.CalledProcessError: Command '/usr/local/bin/pip install altgraph --no-cache-dir --upgrade' returned non-zero exit status 1.
zsh: exit 1     pipupgrade --latest --yes
```

**Comment by max-sixty** [comment]
FWIW, I had this same error and upgrading to the latest `pipupgrade` solved it

**Comment by JayRizzo** [comment]
Hi @max-sixty, 

Yeah, tried that and still having no luck.  it is complaining in the `multiprocessing.pool.RemoteTraceback` about `TypeError: can only concatenate str (not "datetime.timedelta") to str`...

Tried upgrading 
* `/usr/local/opt/python/bin/python3.7 -m pip install --upgrade pip`
* `pip install pipupgrade --upgrade`
* `pip install wheel --upgrade`

Tried uninstalling
* `pip uninstall Flask` (and its associated children)
* `Flask-Babel` `Flask-SocketIO`

it helped it from just hanging but something i have installed may be the case.

I'll keep looking but wanted to share.  Have a better year everyone!  (over the worlds drama)

Stack:

`$ pipupgrade
Checking...
multiprocessing.pool.RemoteTraceback: 
"""
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 143, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.7/site-packages/pipupgrade/model/package.py", line 113, in __init__
    time_difference	= res["_updated_at"] + timedelta(seconds = cache_timeout)
TypeError: can only concatenate str (not "datetime.timedelta") to str
"""

The above exception was the direct cause of the following exception:

.......`

**Comment by ryanpcmcquen** [comment]
I just went back to using this:
```
pip freeze --local | grep -v '^\-e' | cut -d = -f 1 | xargs -n1 pip install -U
pip3 freeze --local | grep -v '^\-e' | cut -d = -f 1 | xargs -n1 pip3 install -U
```

**Comment by max-sixty** [comment]
I'm not sure whether there's another issue where I added something — I do still get this issue. Interestingly it works within a virtual env, but not outside.
