### ISSUE TITLE
pipupgrade: command not found

### ISSUE THREAD

**Issue by francesco1119** [achillesrasquinha/pipupgrade#47]
That is bizarre: I installed pipupgrade right now, pipupgrade is installed but is not recognized:

![2019-11-13 23_11_23-Window](https://user-images.githubusercontent.com/3397477/68808882-fbdbaf80-066a-11ea-9517-1f7ad43ad676.png)

**Comment by ondrovic** [comment]
I have the same issue using on ubuntu WSL for windows 10

**Comment by francesco1119** [comment]
Alright, something has changed on WSL2. 
I followed [this guide]( https://scotch.io/bar-talk/trying-the-new-wsl-2-its-fast-windows-subsystem-for-linux) and I installed WSL2 (Debian).
I now receive a different error: 

```
bobby@AspireS3:~$ pipupgrade
Checking...
2019-11-20 07:35:35,702 | WARNING | Unable to save package name. UNIQUE constraint failed: tabPackage.name
2019-11-20 07:35:35,893 | WARNING | Unable to save package name. UNIQUE constraint failed: tabPackage.name
2019-11-20 07:35:36,022 | WARNING | Unable to save package name. UNIQUE constraint failed: tabPackage.name
2019-11-20 07:35:36,115 | WARNING | Unable to save package name. UNIQUE constraint failed: tabPackage.name
2019-11-20 07:35:36,230 | WARNING | Unable to save package name. UNIQUE constraint failed: tabPackage.name
2019-11-20 07:35:36,339 | WARNING | Unable to save package name. UNIQUE constraint failed: tabPackage.name
2019-11-20 07:35:36,438 | WARNING | Unable to save package name. UNIQUE constraint failed: tabPackage.name
2019-11-20 07:35:36,689 | WARNING | Unable to save package name. UNIQUE constraint failed: tabPackage.name
2019-11-20 07:35:36,769 | WARNING | Unable to save package name. UNIQUE constraint failed: tabPackage.name
2019-11-20 07:35:36,837 | WARNING | Unable to save package name. UNIQUE constraint failed: tabPackage.name
2019-11-20 07:35:36,903 | WARNING | Unable to save package name. UNIQUE constraint failed: tabPackage.name
2019-11-20 07:35:36,988 | WARNING | Unable to save package name. UNIQUE constraint failed: tabPackage.name
2019-11-20 07:35:37,092 | WARNING | Unable to save package name. UNIQUE constraint failed: tabPackage.name
2019-11-20 07:35:37,206 | WARNING | Unable to save package name. UNIQUE constraint failed: tabPackage.name
2019-11-20 07:35:37,295 | WARNING | Unable to save package name. UNIQUE constraint failed: tabPackage.name
2019-11-20 07:35:37,435 | WARNING | Unable to save package name. UNIQUE constraint failed: tabPackage.name
2019-11-20 07:35:37,536 | WARNING | Unable to save package name. UNIQUE constraint failed: tabPackage.name
2019-11-20 07:35:37,616 | WARNING | Unable to save package name. UNIQUE constraint failed: tabPackage.name
2019-11-20 07:35:37,701 | WARNING | Unable to save package name. UNIQUE constraint failed: tabPackage.name
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/usr/local/lib/python3.7/dist-packages/pipupgrade/commands/helper.py", line 106, in get_registry_from_pip
    format = "json", pip_exec = pip_path, output = True)
  File "/usr/local/lib/python3.7/dist-packages/pipupgrade/_pip.py", line 73, in call
    return popen(*params, output = output)
  File "/usr/local/lib/python3.7/dist-packages/pipupgrade/util/system.py", line 70, in popen
    raise sp.CalledProcessError(code, command)
subprocess.CalledProcessError: Command '/usr/bin/pip2 list --outdated --format json' returned non-zero exit status 1.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/pipupgrade", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/pipupgrade/cli/__init__.py", line 14, in wrapper
    return fn(**params)
  File "/usr/local/lib/python3.7/dist-packages/pipupgrade/commands/__init__.py", line 118, in command
    pip_path
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
subprocess.CalledProcessError: Command '/usr/bin/pip2 list --outdated --format json' returned non-zero exit status 1.
```
