### ISSUE TITLE
sqlite3 error on `pipupgrade --latest`

### ISSUE THREAD

**Issue by hhanesand** [achillesrasquinha/pipupgrade#48]
Ran `pipupgrade --latest` after installing :

```
Checking...
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "pipupgrade/commands/helper.py", line 109, in get_registry_from_pip
    installed = True, sync = sync)
  File "pipupgrade/model/registry.py", line 13, in __init__
    for p in packages
  File "pipupgrade/model/registry.py", line 13, in <listcomp>
    for p in packages
  File "pipupgrade/model/package.py", line 40, in __init__
    _db = db.get_connection()
  File "pipupgrade/db.py", line 87, in get_connection
    _CONNECTION.query(query)
  File "pipupgrade/db.py", line 49, in query
    cursor.execute(*args, **kwargs)
sqlite3.OperationalError: database is locked
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pipupgrade", line 8, in <module>
    sys.exit(main())
  File "pipupgrade/cli/__init__.py", line 14, in wrapper
    return fn(**params)
  File "pipupgrade/commands/__init__.py", line 118, in command
    pip_path
  File "multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "multiprocessing/pool.py", line 657, in get
    raise self._value
sqlite3.OperationalError: database is locked
```

```
pip 19.3.1
python 3.7.4
pipupgrade 1.5.2
macOS 10.15.2 (19C57)
```

Only failed once. Worked on second attempt.

**Comment by achillesrasquinha** [comment]
Could you try again with the latest version? If the error persists, please reopen.

**Comment by eabase** [comment]
What's up with this SQLite locking? (where is it done?)
I'm getting this too now...
