### ISSUE TITLE
pipupgrade 1.6.2 has AssertionError on Windows

### ISSUE THREAD

**Issue by wilcoxon** [achillesrasquinha/pipupgrade#55]
I just upgraded pipupgrade to 1.6.2 on Windows 10 (64-bit) running Python 3.8.  Issue #39 is still present (fortunately somebody gave how to fix that one).  In addition, I now get "AssertionError: group argument must be None for now".  From what I can find, this is most likely around parallel/threading but I'm new enough to Python that I can't figure out exactly which call is producing the error.

Edit: I tried downgrading and 1.6.0 and 1.6.1 also have this issue.  I had to drop back to 1.5.2 to get pipupgrade working again.

Here is the full traceback...

`Traceback (most recent call last):
  File "c:\users\wilco\appdata\local\programs\python\python38\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\wilco\appdata\local\programs\python\python38\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\wilco\AppData\Local\Programs\Python\Python38\Scripts\pipupgrade.exe\__main__.py", line 7, in <module>
  File "c:\users\wilco\appdata\local\programs\python\python38\lib\site-packages\pipupgrade\cli\__init__.py", line 15, in wrapper
    return fn(**params)
  File "c:\users\wilco\appdata\local\programs\python\python38\lib\site-packages\pipupgrade\commands\__init__.py", line 143, in command
    with parallel.no_daemon_pool(processes = jobs) as pool:
  File "c:\users\wilco\appdata\local\programs\python\python38\lib\contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "c:\users\wilco\appdata\local\programs\python\python38\lib\site-packages\pipupgrade\parallel.py", line 26, in no_daemon_pool
    with pool(class_ = NoDaemonProcessPool, *args, **kwargs) as p:
  File "c:\users\wilco\appdata\local\programs\python\python38\lib\contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "c:\users\wilco\appdata\local\programs\python\python38\lib\site-packages\pipupgrade\parallel.py", line 20, in pool
    pool = class_(*args, **kwargs)
  File "c:\users\wilco\appdata\local\programs\python\python38\lib\multiprocessing\pool.py", line 212, in __init__
    self._repopulate_pool()
  File "c:\users\wilco\appdata\local\programs\python\python38\lib\multiprocessing\pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "c:\users\wilco\appdata\local\programs\python\python38\lib\multiprocessing\pool.py", line 319, in _repopulate_pool_static
    w = Process(ctx, target=worker,
  File "c:\users\wilco\appdata\local\programs\python\python38\lib\multiprocessing\process.py", line 82, in __init__
    assert group is None, 'group argument must be None for now'
AssertionError: group argument must be None for now`

**Comment by achillesrasquinha** [comment]
I just created a fix in `pipupgrade 1.6.4`. Thanks for posting this error. Could you verify and close once this is fixed?

To upgrade

```
$ pipupgrade --self
```

**Comment by wilcoxon** [comment]
That was a fast fix.  Thanks.

**Comment by achillesrasquinha** [comment]
@wilcoxon could you also please confirm on some issues related to windows? i don't have a working windows machine for myself to have it tested.

**Comment by wilcoxon** [comment]
Sure.  I'm heading to bed now and tomorrow is busy but I should be able to
verify them this week...

**Comment by wilcoxon** [comment]
The only two windows issues I found were:
1) "space in path" which I can't check (easily) since I installed to the default location (eg no space)
2) WSL2 which I can't test since I have WSL1 (I believe WSL2 is still in beta)

**Comment by wilcoxon** [comment]
If there are any that you'd like me to check specifically, just let me know...

**Comment by wilcoxon** [comment]
This is broken in 1.7.1 again.

**Comment by wilcoxon** [comment]
Or maybe not.  I'm now confused.  I did:
1) pipupgrade --self (to 1.7.1)
   * the error fixed in 1.6.5 showed up again
2) easy_install pipugrade==1.6.5
   * the error fixed in 1.6.5 was fixed again
3) pipupgrade --self (to 1.7.1)
   * the error fixed in 1.6.5 was still fixed

No idea what happened.

Closing again...
