### ISSUE TITLE
Possible missing pip module.

### ISSUE THREAD

**Issue by Waples** [achillesrasquinha/pipupgrade#58]
#### What's the bug all about?

missing `pip._internal` module, pipupgrade not functioning.

#### What command led to this issue?

```
$ Traceback (most recent call last):
  File "/home/florian/.local/bin/pipupgrade", line 5, in <module>
    from pipupgrade.__main__ import main
  File "/home/florian/.local/lib/python3.8/site-packages/pipupgrade/__init__.py", line 7, in <module>
    from pipupgrade.__main__    import main
  File "/home/florian/.local/lib/python3.8/site-packages/pipupgrade/__main__.py", line 5, in <module>
    from pipupgrade.commands import command as main
  File "/home/florian/.local/lib/python3.8/site-packages/pipupgrade/commands/__init__.py", line 9, in <module>
    from pipupgrade.commands.helper import (
  File "/home/florian/.local/lib/python3.8/site-packages/pipupgrade/commands/helper.py", line 7, in <module>
    from pipupgrade.model           import Registry
  File "/home/florian/.local/lib/python3.8/site-packages/pipupgrade/model/__init__.py", line 3, in <module>
    from pipupgrade.model.package  import Package
  File "/home/florian/.local/lib/python3.8/site-packages/pipupgrade/model/package.py", line 9, in <module>
    from pipupgrade       import _pip, semver, request as req, db, log
  File "/home/florian/.local/lib/python3.8/site-packages/pipupgrade/_pip.py", line 25, in <module>
    from pip._internal.req             import parse_requirements
ModuleNotFoundError: No module named 'pip._internal'
```

#### Logs

same issue as above.

**Comment by Waples** [comment]
It seems the module parse_requirements has been moved/removed in my version (latest) of `pip`.

additional info:
```
 pip --version
pip 19.3 from /usr/lib/python3.8/site-packages/pip (python 3.8)
```

```
ls /usr/lib/python3.8/site-packages/pip/_internal/req
constructors.py  __init__.py  __pycache__  req_file.py  req_install.py  req_set.py  req_tracker.py  req_uninstall.py
```

**Comment by Waples** [comment]
nevermind, seems I had an orphaned dir
