### ISSUE TITLE
pipupgrade: TypeError: unsupported operand type(s) for +: 'NoneType' and 'datetime.timedelta'

### ISSUE THREAD

**Issue by carloshernandezcu** [achillesrasquinha/pipupgrade#59]
pipupgrade won't work

```
$ pipupgrade --check

Checking...
multiprocessing.pool.RemoteTraceback:
"""
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.7/site-packages/pipupgrade/model/package.py", line 108, in __init__
    time_difference	= res["_updated_at"] + timedelta(seconds = cache_timeout)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'datetime.timedelta'
"""
```

```
$ pipupgrade --self
Checking...
Updating pipupgrade...
pipupgrade upto date.
```

```
$ brew info python
python: stable 3.7.6 (bottled), HEAD
```

Past month pipupgrade was working great. Now it isn't. Maybe the last update has a bug or I'm forgetting to do something?

**Comment by achillesrasquinha** [comment]
Hi Carlos! Could you please use the default `Bug` template that can help us diagnose the issue better?

BTW, can you try `rm -rf $(python -c "from pipupgrade.config import PATH;print(PATH['CACHE']);")`
and try running again

**Comment by carloshernandezcu** [comment]
Hi Achilles, thanks for your quick response.  In this message I'm using the bug template:

#### What's the bug all about?

Past month the pipupgrade tool was working great. Today I try to update pip packages with a cli command and won't work. Some error are shown.

#### What command led to this issue?

```
$ "pipupgrade --latest"
```

#### Logs

*Please paste the logs using `pipupgrade --verbose`*

```
"2020-02-06 13:45:29,933 | INFO | Environment: {'python_version': '3.7.6', 'os': 'Darwin-19.3.0-x86_64-i386-64bit'}
2020-02-06 13:45:29,933 | INFO | Arguments Passed: {'packages': [], 'pip_path': None, 'requirements': None, 'pipfile': None, 'project': None, 'pull_request': False, 'git_username': None, 'git_email': None, 'github_access_token': None, 'github_reponame': None, 'github_username': None, 'target_branch': 'master', 'latest': 0, 'format': 'table', 'all': 0, 'pip': 0, 'self': False, 'jobs': 16, 'user': 0, 'check': 0, 'interactive': 0, 'yes': 0, 'no_included_requirements': 0, 'no_cache': 0, 'no_color': 0, 'output': None, 'ignore_error': 0, 'force': 0, 'verbose': True}
Checking...
2020-02-06 13:45:29,935 | INFO | `pip` executables found: ['/usr/local/bin/pip', '/usr/local/bin/pip3']
2020-02-06 13:45:29,935 | INFO | Using 16 jobs...
2020-02-06 13:45:29,950 | INFO | Fetching installed packages for /usr/local/bin/pip...
2020-02-06 13:45:29,951 | INFO | Fetching installed packages for /usr/local/bin/pip3...
2020-02-06 13:45:29,951 | INFO | Executing command: /usr/local/bin/pip list --outdated --format json
2020-02-06 13:45:29,952 | INFO | Executing command: /usr/local/bin/pip3 list --outdated --format json
2020-02-06 13:45:32,493 | INFO | 2 packages found for /usr/local/bin/pip.
2020-02-06 13:45:32,493 | INFO | 2 packages found for /usr/local/bin/pip3.
2020-02-06 13:45:32,516 | INFO | Initializing Package {'name': 'setuptools', 'version': '44.0.0', 'latest_version': '45.1.0', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2020-02-06 13:45:32,517 | INFO | Initializing Package {'name': 'wheel', 'version': '0.33.6', 'latest_version': '0.34.2', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2020-02-06 13:45:32,517 | INFO | Fetching package setuptools information from DB...
2020-02-06 13:45:32,517 | INFO | Fetching package wheel information from DB...
2020-02-06 13:45:32,517 | INFO | Initializing Package {'name': 'setuptools', 'version': '44.0.0', 'latest_version': '45.1.0', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2020-02-06 13:45:32,517 | INFO | Initializing Package {'name': 'wheel', 'version': '0.33.6', 'latest_version': '0.34.2', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2020-02-06 13:45:32,518 | INFO | Fetching package setuptools information from DB...
2020-02-06 13:45:32,518 | INFO | Fetching package wheel information from DB...
multiprocessing.pool.RemoteTraceback:
"""
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.7/site-packages/pipupgrade/model/package.py", line 108, in __init__
    time_difference	= res["_updated_at"] + timedelta(seconds = cache_timeout)
TypeError: can only concatenate str (not "datetime.timedelta") to str
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.7/site-packages/pipupgrade/commands/helper.py", line 319, in get_registry_from_pip
    build_dependency_tree = build_dependency_tree, jobs = jobs)
  File "/usr/local/lib/python3.7/site-packages/pipupgrade/model/registry.py", line 108, in __init__
    for package in pool.imap_unordered(partial(Package, **args), packages):
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
TypeError: can only concatenate str (not "datetime.timedelta") to str
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/pipupgrade", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/pipupgrade/cli/__init__.py", line 15, in wrapper
    return fn(**params)
  File "/usr/local/lib/python3.7/site-packages/pipupgrade/commands/__init__.py", line 168, in command
    pip_path
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
TypeError: can only concatenate str (not "datetime.timedelta") to str"
```

I tried with your command, also uninstall and install pipupgrade and remove the pip cache folder, after that pipupgrade errors are the same.

**Comment by achillesrasquinha** [comment]
@carloshernandezcu could you please upgrade to `1.6.8` using `pipupgrade --self` and try again?

or simply `pip install --upgrade pipupgrade`

**Comment by carloshernandezcu** [comment]
Ok, the outputs from the commands are:

Upgrade with `$ pipupgrade --self`

```
Checking...
Updating pipupgrade...
pipupgrade upto date.
```

Upgrade with `$ pip install --upgrade pipupgrade`

```
Requirement already up-to-date: pipupgrade in /usr/local/lib/python3.7/site-packages (1.6.8)
```

Trying to upgrades all the packages within the defined pip environment. `$ pipupgrade --check`

```
Checking...
multiprocessing.pool.RemoteTraceback:
"""
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.7/site-packages/pipupgrade/model/package.py", line 113, in __init__
    time_difference	= res["_updated_at"] + timedelta(seconds = cache_timeout)
TypeError: can only concatenate str (not "datetime.timedelta") to str
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.7/site-packages/pipupgrade/commands/helper.py", line 322, in get_registry_from_pip
    build_dependency_tree = build_dependency_tree, jobs = jobs)
  File "/usr/local/lib/python3.7/site-packages/pipupgrade/model/registry.py", line 111, in __init__
    for package in pool.imap_unordered(partial(Package, **args), packages):
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
TypeError: can only concatenate str (not "datetime.timedelta") to str
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/pipupgrade", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/pipupgrade/cli/__init__.py", line 15, in wrapper
    return fn(**params)
  File "/usr/local/lib/python3.7/site-packages/pipupgrade/commands/__init__.py", line 170, in command
    pip_path
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
TypeError: can only concatenate str (not "datetime.timedelta") to str
```

Please, check the results and let me know what could be that pipupgrade isn't working?

**Comment by achillesrasquinha** [comment]
@carloshernandezcu Could you please display me your logs with `pipupgrade --verbose`?

**Comment by carloshernandezcu** [comment]
Hi @achillesrasquinha, this is my log output from `pipupgrade --verbose` :

```
2020-02-14 17:51:37,585 | INFO | `pip` executables found: ['/usr/local/bin/pip', '/usr/local/bin/pip3']
2020-02-14 17:51:37,586 | INFO | Using 16 jobs...
2020-02-14 17:51:37,610 | INFO | Fetching installed packages for /usr/local/bin/pip...
2020-02-14 17:51:37,610 | INFO | Fetching installed packages for /usr/local/bin/pip3...
2020-02-14 17:51:37,611 | INFO | Executing command: /usr/local/bin/pip list --outdated --format json
2020-02-14 17:51:37,611 | INFO | Executing command: /usr/local/bin/pip3 list --outdated --format json
2020-02-14 17:51:39,958 | INFO | 2 packages found for /usr/local/bin/pip3.
2020-02-14 17:51:39,958 | INFO | 2 packages found for /usr/local/bin/pip.
2020-02-14 17:51:39,986 | INFO | Initializing Package {'name': 'setuptools', 'version': '44.0.0', 'latest_version': '45.2.0', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2020-02-14 17:51:39,986 | INFO | Initializing Package {'name': 'wheel', 'version': '0.33.6', 'latest_version': '0.34.2', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2020-02-14 17:51:39,986 | INFO | Fetching package setuptools information from DB...
2020-02-14 17:51:39,987 | INFO | Fetching package wheel information from DB...
2020-02-14 17:51:39,986 | INFO | Initializing Package {'name': 'setuptools', 'version': '44.0.0', 'latest_version': '45.2.0', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2020-02-14 17:51:39,986 | INFO | Initializing Package {'name': 'wheel', 'version': '0.33.6', 'latest_version': '0.34.2', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2020-02-14 17:51:39,987 | INFO | Fetching package setuptools information from DB...
2020-02-14 17:51:39,987 | INFO | Fetching package wheel information from DB...
multiprocessing.pool.RemoteTraceback:
"""
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.7/site-packages/pipupgrade/model/package.py", line 113, in __init__
    time_difference	= res["_updated_at"] + timedelta(seconds = cache_timeout)
TypeError: can only concatenate str (not "datetime.timedelta") to str
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.7/site-packages/pipupgrade/commands/helper.py", line 322, in get_registry_from_pip
    build_dependency_tree = build_dependency_tree, jobs = jobs)
  File "/usr/local/lib/python3.7/site-packages/pipupgrade/model/registry.py", line 111, in __init__
    for package in pool.imap_unordered(partial(Package, **args), packages):
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
TypeError: can only concatenate str (not "datetime.timedelta") to str
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/pipupgrade", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/pipupgrade/cli/__init__.py", line 15, in wrapper
    return fn(**params)
  File "/usr/local/lib/python3.7/site-packages/pipupgrade/commands/__init__.py", line 170, in command
    pip_path
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
TypeError: can only concatenate str (not "datetime.timedelta") to str
```

I appreciate your time to resolve this issue.

**Comment by carloshernandezcu** [comment]
Hello! I downgrade the version to `1.6.7` and now pipupgrade is working again. For some reason `1.6.8` wasn't working on my computer (macOS Catalina). Thanks a lot for your support.

**Comment by sidler-mozilla** [comment]
I am getting this same behavior on 1.7.1.  I can confirm that I get exactly what is described here: https://github.com/achillesrasquinha/pipupgrade/issues/59#issuecomment-586020317

**Comment by carloshernandezcu** [comment]
I got the same error on 1.7.1, after some work, I fixed the problem uninstalling every package using pip, and pip itself. Then, I uninstall and reinstall the python version I use.
```
$ brew uninstall --ignore-dependencies python
$ brew install python
```
And finally, pipupgrade worked!
