### ISSUE TITLE
Command returned non zero exit status since pip is not callable (LISTED POTENTIAL FIX)

### ISSUE THREAD

**Issue by Column01** [achillesrasquinha/pipupgrade#60]
#### What's the bug all about?
When running any command that checks the pip packages, I get an error since when running the command `pip list --format json` it says the module pip is not callable. 
This could be fixed by using this instead: `/usr/bin/python3 -m pip list --format json`

#### What command led to this issue?

*Please type the exact command that led to this issue.*

```
$ pipupgrade -a
OR
$ pipupgrade --check
OR
$ pipupgrade --latest --yes
```

#### Logs

*Please paste the logs using `pipupgrade --verbose`*
```
pi@raspberrypi:~/<REDACTED> $ pipupgrade -a --verbose
2020-02-05 13:07:56,317 | INFO | Environment: {'python_version': '3.7.3', 'os': 'Linux-4.19.75-v7l+-armv7l-with-debian-10.1'}
2020-02-05 13:07:56,317 | INFO | Arguments Passed: {'packages': [], 'pip_path': None, 'requirements': None, 'pipfile': None, 'project': None, 'pull_request': False, 'git_username': None, 'git_email': None, 'github_access_token': None, 'github_reponame': None, 'github_username': None, 'target_branch': 'master', 'latest': 0, 'format': 'table', 'all': True, 'pip': 0, 'self': False, 'jobs': 4, 'user': 0, 'check': 0, 'interactive': 0, 'yes': 0, 'no_included_requirements': 0, 'no_cache': 0, 'no_color': 0, 'output': None, 'ignore_error': 0, 'force': 0, 'verbose': True}
Checking...
2020-02-05 13:07:56,322 | INFO | `pip` executables found: ['/usr/bin/pip', '/usr/bin/pip3', '/usr/bin/pip2']
2020-02-05 13:07:56,322 | INFO | Using 4 jobs...
2020-02-05 13:07:56,356 | INFO | Fetching installed packages for /usr/bin/pip...
2020-02-05 13:07:56,356 | INFO | Fetching installed packages for /usr/bin/pip3...
2020-02-05 13:07:56,357 | INFO | Fetching installed packages for /usr/bin/pip2...
2020-02-05 13:07:56,358 | INFO | Executing command: /usr/bin/pip list --format json
2020-02-05 13:07:56,359 | INFO | Executing command: /usr/bin/pip3 list --format json
2020-02-05 13:07:56,359 | INFO | Executing command: /usr/bin/pip2 list --format json
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/pi/.local/lib/python3.7/site-packages/pipupgrade/commands/helper.py", line 309, in get_registry_from_pip
    format = "json", pip_exec = pip_path, output = True)
  File "/home/pi/.local/lib/python3.7/site-packages/pipupgrade/_pip.py", line 74, in call
    output = popen(*params, output = output, raise_err = raise_err)
  File "/home/pi/.local/lib/python3.7/site-packages/pipupgrade/util/system.py", line 79, in popen
    raise PopenError(code, command)
pipupgrade.exception.PopenError: Command '/usr/bin/pip3 list --format json' returned non-zero exit status 1.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/.local/bin/pipupgrade", line 10, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.7/site-packages/pipupgrade/cli/__init__.py", line 15, in wrapper
    return fn(**params)
  File "/home/pi/.local/lib/python3.7/site-packages/pipupgrade/commands/__init__.py", line 168, in command
    pip_path
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
pipupgrade.exception.PopenError: Command '/usr/bin/pip3 list --format json' returned non-zero exit status 1.
```

**Comment by achillesrasquinha** [comment]
@Column01 What version of `pip3` are you using? Display it using `pip3 --version`

**Comment by Column01** [comment]
My apologizes, PIP decided to add a stupid directory to my path that overwrote the default pip one. Fixed it now :|

**Comment by achillesrasquinha** [comment]
Does this mean it's working?

**Comment by Column01** [comment]
Actually, no it isn't. Though this was the problem but it isn't. Tried with 18.1 and now with the latest, same error but now it's saying pip2 which is using 18.1 still
```pi@raspberrypi:~ $ /usr/bin/pip3 --version
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
pip 20.0.2 from /home/pi/.local/lib/python3.7/site-packages/pip (python 3.7)
pi@raspberrypi:~ $ pipupgrade --check
Checking...
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/pi/.local/lib/python3.7/site-packages/pipupgrade/commands/helper.py", line 309, in get_registry_from_pip
    format = "json", pip_exec = pip_path, output = True)
  File "/home/pi/.local/lib/python3.7/site-packages/pipupgrade/_pip.py", line 74, in call
    output = popen(*params, output = output, raise_err = raise_err)
  File "/home/pi/.local/lib/python3.7/site-packages/pipupgrade/util/system.py", line 79, in popen
    raise PopenError(code, command)
pipupgrade.exception.PopenError: Command '/usr/bin/pip2 list --outdated --format json' returned non-zero exit status 2.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/.local/bin/pipupgrade", line 10, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.7/site-packages/pipupgrade/cli/__init__.py", line 15, in wrapper
    return fn(**params)
  File "/home/pi/.local/lib/python3.7/site-packages/pipupgrade/commands/__init__.py", line 168, in command
    pip_path
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
pipupgrade.exception.PopenError: Command '/usr/bin/pip2 list --outdated --format json' returned non-zero exit status 2.```

**Comment by Column01** [comment]
I have a feeling this is a Rasbian issue. It appears to have two installs of python present. One in `/usr/` and one in `/home/pi/.local/`

Removing python 2.7 has fixed the issue, however.

**Comment by Column01** [comment]
hard to track down... I've had another error happen and I forgot to report it since it was late. Will try to reproduce it

**Comment by Column01** [comment]
Hey, me from the future. This was a configuration error. Closing as it's not relevant to this repository

**Comment by walksonair** [comment]
I'm having a similar issue and suspect configuration. Can you shed some light on what you did to resolve this issue?

**Comment by Column01** [comment]
Like I said, I uninstalled python 2.7 and it worked fine. Just make sure the `/usr/bin` has a `pip` or `pip3` in it, if not that could be why

**Comment by Column01** [comment]
though I haven't used this program in ages so I have no idea if my changes I made still work
