### ISSUE TITLE
WARNING | Unable to fetch package name. disk I/O error

### ISSUE THREAD

**Issue by E3V3A** [achillesrasquinha/pipupgrade#64]
Running this on Cygwin...

```
$ pip install pipupgrade
Collecting pipupgrade
  Downloading pipupgrade-1.6.8-py3-none-any.whl (37 kB)
Installing collected packages: pipupgrade
  WARNING: The script pipupgrade is installed in '/cygdrive/c/cygwin64/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pipupgrade-1.6.8

$ pipupgrade
Checking...
2020-03-18 18:52:45,438 | WARNING | Unable to fetch package name. disk I/O error
2020-03-18 18:52:45,438 | WARNING | Unable to fetch package name. disk I/O error
2020-03-18 18:52:45,438 | WARNING | Unable to fetch package name. disk I/O error
2020-03-18 18:52:45,439 | WARNING | Unable to fetch package name. disk I/O error
2020-03-18 18:52:45,439 | WARNING | Unable to fetch package name. disk I/O error
2020-03-18 18:52:45,439 | WARNING | Unable to fetch package name. disk I/O error
2020-03-18 18:52:45,441 | WARNING | Unable to fetch package name. no such table: tabPackage
...

Source: Installed Distributions (/usr/bin/pip)

Name                          Current Version Latest Version Home Page
----------------------------- --------------- -------------- -------------------------------------------------
Babel                         2.7.0           2.8.0          http://babel.pocoo.org/
beautifulsoup4                4.8.1           4.8.2          http://www.crummy.com/software/BeautifulSoup/bs4/
...

```

#### Logs

*Please paste the logs using `pipupgrade --verbose`*

```
"<YOUR LOGS HERE>"
```

**Comment by achillesrasquinha** [comment]
Personally haven't tested this on Cygwin, would need to figure out an environment to do so.

**Comment by achillesrasquinha** [comment]
By best case is a corrupted cache for now. `rm -rf ~/.pipupgrade` and try again? It seems like a SQLite issue related to Cygwin.

**Comment by E3V3A** [comment]
> remove cahce

Tried, same thing

> It seems like a SQLite issue

Nope. I never had an issue with `sqlite3` on Cygwin. I don't think it is sqlite, it must be a permission thing, although permissions are *not really used* under Cygwin. 

Tried changing permissions, same thing.

Where is the data base used in the code? 
I can't find the calls to sqlite...

**Comment by E3V3A** [comment]
Can you guys post the results from: 
```bash
echo ".vfsinfo" | sqlite3 db.db
echo ".show" | sqlite3 db.db
echo ".stats on" | sqlite3 db.db
echo ".show" | sqlite3 db.db
echo ".dbinfo" | sqlite3 db.db
echo ".dbconfig" | sqlite3 db.db
echo ".limit" | sqlite3 db.db
echo ".mode" | sqlite3 db.db
echo ".stats" | sqlite3 db.db
```

PS. What is *your* default location for the `db.db` file (on windows)?

**Comment by E3V3A** [comment]
Don't you need to do `db.commit()` and then `db.close()`? I  don't see those?

**Comment by E3V3A** [comment]
I tired to give full permissions with: 
```bash
icacls.exe "C:\cygwin64\home\xxxx\.pipupgrade" /grant Everyone:F /T

```

Same problem:

```
Checking...
2020-03-26 17:07:30,483 | INFO | `pip` executables found: ['/usr/bin/pip3']
2020-03-26 17:07:30,484 | INFO | Using 1 jobs...
2020-03-26 17:07:30,514 | INFO | Fetching installed packages for /usr/bin/pip3...
2020-03-26 17:07:30,514 | INFO | Executing command: /usr/bin/pip3 list --outdated --format json
2020-03-26 17:07:49,407 | INFO | 44 packages found for /usr/bin/pip3.
2020-03-26 17:07:49,435 | INFO | Initializing Package {'name': 'py', 'version': '1.8.0', 'latest_version': '1.8.1', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2020-03-26 17:07:49,435 | INFO | Fetching package py information from DB...
2020-03-26 17:07:49,435 | WARNING | Unable to fetch package name. disk I/O error
2020-03-26 17:07:49,435 | INFO | Fetching PyPI info for package <Package py (1.8.0)>...
2020-03-26 17:07:49,436 | INFO | Dispatching GET request with arguments ('https://pypi.org/pypi/py/json',) and parameters {}.
2020-03-26 17:07:49,852 | INFO | Attempting to INSERT package <Package py (1.8.0)> into database with values: ('py', '1.8.1', 'http://py.readthedocs.io/', datetime.datetime(2020, 3, 26, 17, 7, 49, 852166), datetime.datetime(2020, 3, 26, 17, 7, 49, 852171)).
2020-03-26 17:07:49,852 | WARNING | Unable to save package name. disk I/O error
2020-03-26 17:07:49,869 | INFO | Packages within `pip` /usr/bin/pip3 found: [<Package py (1.8.0)>]...
2020-03-26 17:07:49,889 | INFO | Updating registries: [<pipupgrade.model.registry.Registry object at 0x6ffffea80040>]...
Traceback (most recent call last):
  File "/usr/bin/pipupgrade", line 8, in <module>
    sys.exit(main())
  File "/cygdrive/c/cygwin64/lib/python3.8/site-packages/pipupgrade/cli/__init__.py", line 15, in wrapper
    return fn(**params)
  File "/cygdrive/c/cygwin64/lib/python3.8/site-packages/pipupgrade/commands/__init__.py", line 178, in command
    update_registry(registry, yes = yes, user = user, check = check,
  File "/cygdrive/c/cygwin64/lib/python3.8/site-packages/pipupgrade/commands/helper.py", line 210, in update_registry
    packages = [p for p in packages if p["name"] in filter_]
  File "/cygdrive/c/cygwin64/lib/python3.8/site-packages/pipupgrade/commands/helper.py", line 210, in <listcomp>
    packages = [p for p in packages if p["name"] in filter_]
TypeError: 'Package' object is not subscriptable
```
