### ISSUE TITLE
Include build instructions

### ISSUE THREAD

**Issue by ejuarezg** [achillesrasquinha/pipupgrade#69]
Hi, can you include instructions to build pipupgrade manually? I am running into some errors using the last release and would like to build it manually to see if the errors have been addressed in recent commits.

Thanks!

**Comment by achillesrasquinha** [comment]
What errors do you face?

**Comment by ejuarezg** [comment]
I'm running `pipupgrade itunespy` and I get the following output:

```
Checking...
Installed Distributions (/usr/bin/pip3) upto date.
Traceback (most recent call last):
  File "/home/user/.conda/envs/random/bin/pipupgrade", line 8, in <module>
    sys.exit(main())
  File "/home/user/.conda/envs/random/lib/python3.6/site-packages/pipupgrade/cli/__init__.py", line 15, in wrapper
    return fn(**params)
  File "/home/user/.conda/envs/random/lib/python3.6/site-packages/pipupgrade/commands/__init__.py", line 182, in command
    upgrade_type = upgrade_type
  File "/home/user/.conda/envs/random/lib/python3.6/site-packages/pipupgrade/commands/helper.py", line 210, in update_registry
    packages = [p for p in packages if p["name"] in filter_]
  File "/home/user/.conda/envs/random/lib/python3.6/site-packages/pipupgrade/commands/helper.py", line 210, in <listcomp>
    packages = [p for p in packages if p["name"] in filter_]
TypeError: 'Package' object is not subscriptable
```

**Comment by achillesrasquinha** [comment]
Added build instructions [here](https://github.com/achillesrasquinha/pipupgrade/blob/master/docs/source/INSTALLATION.md).

**Comment by ejuarezg** [comment]
Thanks for the instructions. I tried to build module but it failed with error
```
Traceback (most recent call last):
  File "setup.py", line 102, in <module>
    dev = get_dependencies(type_ = "development")
  File "setup.py", line 54, in get_dependencies
    str(ir.req) for ir in parse_requirements(path, session = "hack")
  File "setup.py", line 55, in <listcomp>
    if str(ir.req) not in requirements
AttributeError: 'ParsedRequirement' object has no attribute 'req'
```
I believe this is due to the empty file `requirements.txt`.

Also, the command `curl -OL https://github.com/achillesrasquinha/tarball/ccapi`  in the instructions did not work for downloading the tarball. Instead, I had to use `curl -OL https://github.com/achillesrasquinha/pipupgrade/tarball/master`.

**Comment by achillesrasquinha** [comment]
Updated them.

**Comment by achillesrasquinha** [comment]
Fixed setup.py hack!
