### ISSUE TITLE
after pipupgrade --self executable cannot be found

### ISSUE THREAD

**Issue by eabase** [achillesrasquinha/pipupgrade#81]
#### What's the bug all about?

After I updated _pipupgrade_  from `1.7.1` to  `1.7.4`, using Py3.8 on Cygwin, the executable can no longer be found. 
In fact it find the the wrapper in the path, but then it is not able to execute it. 

#### What command led to this issue?

```
pipupgrade  --self
```

#### Logs

```bash
$ pipupgrade
-bash: /usr/bin/pipupgrade: No such file or directory

$ which pipupgrade
/usr/local/bin/pipupgrade

$ cat `which pipupgrade`

#!/usr/bin/python3.8.exe
# -*- coding: utf-8 -*-
import re
import sys
from pipupgrade.__main__ import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

**Comment by eabase** [comment]
Strangely enough, even though it is in the path, it cannot be executed there. 
Instead I managed to get it to execute with:
```bash
 python `which pipupgrade` -c -l
```

This yield a lot of errors:

<details>
<summary>Click to see</summary>

```bash

$ python `which pipupgrade` -c -l

Checking...
2020-12-14 00:19:58,136 | WARNING | Unable to fetch package name. disk I/O error
2020-12-14 00:19:58,136 | WARNING | Unable to fetch package name. disk I/O error
2020-12-14 00:19:58,136 | WARNING | Unable to fetch package name. disk I/O error
2020-12-14 00:19:58,136 | WARNING | Unable to fetch package name. disk I/O error
2020-12-14 00:19:58,156 | WARNING | Unable to fetch package name. disk I/O error
2020-12-14 00:19:58,157 | WARNING | Unable to fetch package name. disk I/O error
2020-12-14 00:19:58,157 | WARNING | Unable to fetch package name. disk I/O error
2020-12-14 00:19:58,157 | WARNING | Unable to fetch package name. disk I/O error
2020-12-14 00:19:58,470 | WARNING | Unable to save package name. disk I/O error
...
2020-12-14 00:20:08,625 | WARNING | Unable to fetch package name. database is locked
2020-12-14 00:20:08,625 | WARNING | Unable to fetch package name. database is locked
2020-12-14 00:20:09,024 | WARNING | Unable to save package name. database is locked
2020-12-14 00:20:19,305 | WARNING | Unable to save package name. database is locked

```

followed by the packages:

```
Source: Installed Distributions (/usr/local/bin/pip3)

Name                          Current Version Latest Version Home Page
----------------------------- --------------- -------------- -------------------------------------------------
appdirs                       1.4.3           1.4.4          http://github.com/ActiveState/appdirs
attrs                         19.3.0          20.3.0         https://www.attrs.org/
Babel                         2.8.0           2.9.0          http://babel.pocoo.org/
beautifulsoup4                4.9.2           4.9.3          http://www.crummy.com/software/BeautifulSoup/bs4/
...
```
</details>

**Comment by eabase** [comment]
For `Disk IO Error`, I got this log snippet:
```
2020-12-14 00:35:13,541 | WARNING | Unable to save package name. disk I/O error
2020-12-14 00:35:13,587 | WARNING | Unable to save package name. disk I/O error
Traceback (most recent call last):
  File "/usr/local/bin/pipupgrade", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/pipupgrade/cli/__init__.py", line 15, in wrapper
    return fn(**params)
  File "/usr/local/lib/python3.8/site-packages/pipupgrade/commands/__init__.py", line 181, in command
    update_registry(registry, yes = yes, user = user, check = check,
  File "/usr/local/lib/python3.8/site-packages/pipupgrade/commands/helper.py", line 210, in update_registry
    packages = [p for p in packages if p["name"] in filter_]
  File "/usr/local/lib/python3.8/site-packages/pipupgrade/commands/helper.py", line 210, in <listcomp>
    packages = [p for p in packages if p["name"] in filter_]
TypeError: 'Package' object is not subscriptable
```

**Comment by eabase** [comment]
@achillesrasquinha 

I think there are some problems in your DB queries etc.  

Both these errors:
```
IntegrityError       = sqlite3.IntegrityError
OperationalError     = sqlite3.OperationalError
```
are stemming from that file.

Things you need to check:

* make sure you close the DB connection (not only the cursor)
* make sure you're not having threads making multiple access
* make sure that connection is closed or re-opened properly after an exception. (I don't see this in your code)
* enable sqlite3 logging using the PRAGMA for that. 
* If you are using foreign keys, you need to ensure that the _pragama_ is enabled, as it is **disabled by default**:
  `PRAGMA foreign_keys=ON;`
* **Do not use** `DATETIME` or `TIMESTAMP`! SQLite3 [does not have them!](https://www.sqlite.org/quirks.html) 

> SQLite has no DATETIME datatype. Instead, dates and times can be stored in any of these ways:
>
>    As a TEXT string in the ISO-8601 format. Example: '2018-04-02 12:13:46'.
>    As an INTEGER number of seconds since 1970 (also known as "unix time").
>    As a REAL value that is the fractional Julian day number. 

* Please add **`Cygwin`** to the list of available systems [here](https://github.com/achillesrasquinha/pipupgrade/blob/7a4ccf936378238aea96ada97b6c5b57b16abd63/src/pipupgrade/_compat.py#L109-L114)

https://github.com/achillesrasquinha/pipupgrade/blob/7a4ccf936378238aea96ada97b6c5b57b16abd63/src/pipupgrade/_compat.py#L109-L114


This check need to be done as a *sub-string* because `platform.system()` returns **`CYGWIN_NT-6.3-9600`** for W8.1 and something else for Win10. However, it is probably much better to use either `os.platform()` or `sys.platform()` for this check!

```
# On Cygwin py3.8
os.name:             posix
os.sys.platform:     cygwin
sys.platform:        cygwin

# On Win/powershell py3.7
os.name:             nt
os.sys.platform:     win32
sys.platform:        win32
```

* Also the `package.py` file seem to need some cleaning up. It's almost unreadable (at least from github):
* https://github.com/achillesrasquinha/pipupgrade/blob/master/src/pipupgrade/model/package.py

* One last thing, you seem to be very fond of using back-ticks (```) in both you SQL tables and in your DB queries. I don't think that is a good idea, and in fact quite unusual. Single and double quotes are more than enough even for advanced queries.  Maybe try to remove them. (The quotes are also completely redundant for names and columns in tables, when they are simple words.)

**Comment by achillesrasquinha** [comment]
Thank you for a clear review! I've abided to using `TEXT` instead of `DATETIME` or `TIMESTAMP`. I'll need to revisit a little more on your comments and see a good review and help for the same.
