### ISSUE TITLE
Exception in thread Thread-5

### ISSUE THREAD

**Issue by RashiqAzhan** [achillesrasquinha/pipupgrade#83]
#### What's the bug all about?

pipupgrade won't update/upgrade anything.

#### What command led to this issue?

Happens with all the commands.

```
$ pipupgrade --latest
```

#### Logs

*Please paste the logs using `pipupgrade --verbose`*

```
2020-12-15 15:49:36,495 | INFO | Executing command: C:\Python310\Scripts\pip.EXE --version
2020-12-15 15:49:36,723 | INFO | Executing command: C:\Python310\Scripts\pip3.EXE --version
2020-12-15 15:49:36,942 | INFO | Environment: {'version': '1.7.4', 'python_version': '3.10.0a3', 'os': 'Windows-10-10.0.19041-SP0', 'config': {'path': {'BASE': 'c:\\python310\\lib\\site-packages\\pipupgrade', 'DATA': 'c:\\python310\\lib\\site-packages\\pipupgrade\\data', 'CACHE': 'C:\\Users\\user\\.pipupgrade'}}, 'pip_executables': [{'executable': 'C:\\Python310\\Scripts\\pip.EXE', 'version': 'pip 20.3.3 from c:\\python310\\lib\\site-packages\\pip (python 3.10)'}, {'executable': 'C:\\Python310\\Scripts\\pip3.EXE', 'version': 'pip 20.3.3 from c:\\python310\\lib\\site-packages\\pip (python 3.10)'}], 'settings': {'settings': {'version': '1.7.4', 'cache_timeout': '86400', 'jobs': '64'}}}
2020-12-15 15:49:36,943 | INFO | Arguments Passed: {'packages': [], 'ignore': None, 'pip_path': None, 'requirements': None, 'pipfile': None, 'project': None, 'pull_request': False, 'git_username': None, 'git_email': None, 'github_access_token': None, 'github_reponame': None, 'github_username': None, 'target_branch': 'master', 'upgrade_type': ['minor', 'patch'], 'latest': 0, 'format': 'table', 'all': 0, 'pip': 0, 'self': False, 'jobs': 64, 'user': 0, 'check': 0, 'interactive': 0, 'yes': 0, 'no_included_requirements': 0, 'no_cache': 0, 'no_color': 0, 'output': None, 'ignore_error': 0, 'force': 0, 'verbose': True}
Checking...
2020-12-15 15:49:36,945 | INFO | `pip` executables found: ['C:\\Python310\\Scripts\\pip.EXE', 'C:\\Python310\\Scripts\\pip3.EXE']
2020-12-15 15:49:36,945 | INFO | Using 64 jobs...
Exception in thread Thread-5 (_handle_workers):
2020-12-15 15:49:38,179 | INFO | Fetching installed packages for C:\Python310\Scripts\pip.EXE...
2020-12-15 15:49:38,179 | INFO | Fetching installed packages for C:\Python310\Scripts\pip3.EXE...
Traceback (most recent call last):
  File "c:\python310\lib\threading.py", line 972, in _bootstrap_inner
2020-12-15 15:49:38,180 | INFO | Executing command: C:\Python310\Scripts\pip.EXE list --outdated --format json
2020-12-15 15:49:38,180 | INFO | Executing command: C:\Python310\Scripts\pip3.EXE list --outdated --format json
    self.run()
  File "c:\python310\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "c:\python310\lib\multiprocessing\pool.py", line 519, in _handle_workers
    cls._wait_for_updates(current_sentinels, change_notifier)
  File "c:\python310\lib\multiprocessing\pool.py", line 499, in _wait_for_updates
    wait(sentinels, timeout=timeout)
  File "c:\python310\lib\multiprocessing\connection.py", line 884, in wait
    ready_handles = _exhaustive_wait(waithandle_to_obj.keys(), timeout)
  File "c:\python310\lib\multiprocessing\connection.py", line 816, in _exhaustive_wait
    res = _winapi.WaitForMultipleObjects(L, False, timeout)
ValueError: need at most 63 handles, got a sequence of length 66
2020-12-15 15:49:40,529 | INFO | 12 packages found for C:\Python310\Scripts\pip3.EXE.
2020-12-15 15:49:40,727 | INFO | 12 packages found for C:\Python310\Scripts\pip.EXE.
Exception in thread Thread-3 (_handle_workers):
Traceback (most recent call last):
  File "c:\python310\lib\threading.py", line 972, in _bootstrap_inner
2020-12-15 15:49:42,274 | INFO | Initializing Package {'name': 'cachetools', 'version': '4.1.1', 'latest_version': '4.2.0', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2020-12-15 15:49:42,274 | INFO | Initializing Package {'name': 'certifi', 'version': '2020.11.8', 'latest_version': '2020.12.5', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2020-12-15 15:49:42,275 | INFO | Initializing Package {'name': 'chardet', 'version': '3.0.4', 'latest_version': '4.0.0', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2020-12-15 15:49:42,275 | INFO | Initializing Package {'name': 'fonttools', 'version': '4.18.0', 'latest_version': '4.18.1', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2020-12-15 15:49:42,275 | INFO | Initializing Package {'name': 'Faker', 'version': '4.18.0', 'latest_version': '5.0.2', 'latest_filetype': 'wheel'} of type <class 'dict'>...
    self.run()
2020-12-15 15:49:42,275 | INFO | Fetching package cachetools information from DB...
2020-12-15 15:49:42,275 | INFO | Fetching package certifi information from DB...
2020-12-15 15:49:42,275 | INFO | Fetching package chardet information from DB...
2020-12-15 15:49:42,275 | INFO | Initializing Package {'name': 'google-api-python-client', 'version': '1.7.11', 'latest_version': '1.12.8', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2020-12-15 15:49:42,275 | INFO | Fetching package fonttools information from DB...
2020-12-15 15:49:42,275 | INFO | Initializing Package {'name': 'google-auth', 'version': '1.23.0', 'latest_version': '1.24.0', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2020-12-15 15:49:42,275 | INFO | Initializing Package {'name': 'google-auth-oauthlib', 'version': '0.4.0', 'latest_version': '0.4.2', 'latest_filetype': 'wheel'} of type <class 'dict'>...
  File "c:\python310\lib\threading.py", line 910, in run
2020-12-15 15:49:42,275 | INFO | Fetching package Faker information from DB...
2020-12-15 15:49:42,276 | INFO | Fetching package google-auth-oauthlib information from DB...
2020-12-15 15:49:42,275 | INFO | Initializing Package {'name': 'protobuf', 'version': '3.9.2', 'latest_version': '3.14.0', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2020-12-15 15:49:42,275 | INFO | Initializing Package {'name': 'setuptools', 'version': '47.1.0', 'latest_version': '51.0.0', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2020-12-15 15:49:42,275 | INFO | Initializing Package {'name': 'urllib3', 'version': '1.24.2', 'latest_version': '1.26.2', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2020-12-15 15:49:42,276 | INFO | Fetching package google-api-python-client information from DB...
2020-12-15 15:49:42,276 | INFO | Using cached info for package <Package cachetools (4.1.1)>.
2020-12-15 15:49:42,276 | INFO | Fetching package google-auth information from DB...
2020-12-15 15:49:42,276 | INFO | Using cached info for package <Package certifi (2020.11.8)>.
2020-12-15 15:49:42,276 | INFO | Using cached info for package <Package chardet (3.0.4)>.
2020-12-15 15:49:42,275 | INFO | Initializing Package {'name': 'lazy-object-proxy', 'version': '1.4.3', 'latest_version': '1.5.2', 'latest_filetype': 'sdist'} of type <class 'dict'>...
2020-12-15 15:49:42,276 | INFO | Using cached info for package <Package fonttools (4.18.0)>.
    self._target(*self._args, **self._kwargs)
2020-12-15 15:49:42,276 | INFO | Fetching package protobuf information from DB...
2020-12-15 15:49:42,276 | INFO | Using cached info for package <Package Faker (4.18.0)>.
2020-12-15 15:49:42,276 | INFO | Using cached info for package <Package google-auth-oauthlib (0.4.0)>.
2020-12-15 15:49:42,276 | INFO | Fetching package setuptools information from DB...
2020-12-15 15:49:42,276 | INFO | Fetching package urllib3 information from DB...
2020-12-15 15:49:42,277 | INFO | Using cached info for package <Package google-api-python-client (1.7.11)>.
2020-12-15 15:49:42,277 | INFO | Using cached info for package <Package google-auth (1.23.0)>.
2020-12-15 15:49:42,277 | INFO | Fetching package lazy-object-proxy information from DB...
  File "c:\python310\lib\multiprocessing\pool.py", line 519, in _handle_workers
2020-12-15 15:49:42,278 | INFO | Using cached info for package <Package protobuf (3.9.2)>.
2020-12-15 15:49:42,278 | INFO | Using cached info for package <Package urllib3 (1.24.2)>.
2020-12-15 15:49:42,278 | INFO | Using cached info for package <Package setuptools (47.1.0)>.
2020-12-15 15:49:42,278 | INFO | Using cached info for package <Package lazy-object-proxy (1.4.3)>.
    cls._wait_for_updates(current_sentinels, change_notifier)
  File "c:\python310\lib\multiprocessing\pool.py", line 499, in _wait_for_updates
    wait(sentinels, timeout=timeout)
  File "c:\python310\lib\multiprocessing\connection.py", line 884, in wait
    ready_handles = _exhaustive_wait(waithandle_to_obj.keys(), timeout)
  File "c:\python310\lib\multiprocessing\connection.py", line 816, in _exhaustive_wait
    res = _winapi.WaitForMultipleObjects(L, False, timeout)
ValueError: need at most 63 handles, got a sequence of length 66
Exception in thread Thread-3 (_handle_workers):
Traceback (most recent call last):
  File "c:\python310\lib\threading.py", line 972, in _bootstrap_inner
2020-12-15 15:49:43,669 | INFO | Initializing Package {'name': 'cachetools', 'version': '4.1.1', 'latest_version': '4.2.0', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2020-12-15 15:49:43,669 | INFO | Initializing Package {'name': 'certifi', 'version': '2020.11.8', 'latest_version': '2020.12.5', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2020-12-15 15:49:43,669 | INFO | Initializing Package {'name': 'chardet', 'version': '3.0.4', 'latest_version': '4.0.0', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2020-12-15 15:49:43,669 | INFO | Initializing Package {'name': 'Faker', 'version': '4.18.0', 'latest_version': '5.0.2', 'latest_filetype': 'wheel'} of type <class 'dict'>...
    self.run()
  File "c:\python310\lib\threading.py", line 910, in run
2020-12-15 15:49:43,670 | INFO | Initializing Package {'name': 'google-api-python-client', 'version': '1.7.11', 'latest_version': '1.12.8', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2020-12-15 15:49:43,670 | INFO | Initializing Package {'name': 'google-auth', 'version': '1.23.0', 'latest_version': '1.24.0', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2020-12-15 15:49:43,672 | INFO | Fetching package google-api-python-client information from DB...
2020-12-15 15:49:43,670 | INFO | Initializing Package {'name': 'lazy-object-proxy', 'version': '1.4.3', 'latest_version': '1.5.2', 'latest_filetype': 'sdist'} of type <class 'dict'>...
2020-12-15 15:49:43,671 | INFO | Initializing Package {'name': 'setuptools', 'version': '47.1.0', 'latest_version': '51.0.0', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2020-12-15 15:49:43,670 | INFO | Initializing Package {'name': 'protobuf', 'version': '3.9.2', 'latest_version': '3.14.0', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2020-12-15 15:49:43,671 | INFO | Initializing Package {'name': 'urllib3', 'version': '1.24.2', 'latest_version': '1.26.2', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2020-12-15 15:49:43,671 | INFO | Fetching package cachetools information from DB...
2020-12-15 15:49:43,672 | INFO | Fetching package certifi information from DB...
2020-12-15 15:49:43,672 | INFO | Fetching package chardet information from DB...
2020-12-15 15:49:43,670 | INFO | Initializing Package {'name': 'fonttools', 'version': '4.18.0', 'latest_version': '4.18.1', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2020-12-15 15:49:43,672 | INFO | Fetching package Faker information from DB...
2020-12-15 15:49:43,670 | INFO | Initializing Package {'name': 'google-auth-oauthlib', 'version': '0.4.0', 'latest_version': '0.4.2', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2020-12-15 15:49:43,673 | INFO | Using cached info for package <Package cachetools (4.1.1)>.
2020-12-15 15:49:43,673 | INFO | Using cached info for package <Package chardet (3.0.4)>.
2020-12-15 15:49:43,673 | INFO | Fetching package lazy-object-proxy information from DB...
2020-12-15 15:49:43,673 | INFO | Fetching package setuptools information from DB...
2020-12-15 15:49:43,675 | INFO | Using cached info for package <Package lazy-object-proxy (1.4.3)>.
2020-12-15 15:49:43,673 | INFO | Fetching package protobuf information from DB...
2020-12-15 15:49:43,673 | INFO | Fetching package urllib3 information from DB...
2020-12-15 15:49:43,673 | INFO | Fetching package fonttools information from DB...
2020-12-15 15:49:43,673 | INFO | Using cached info for package <Package certifi (2020.11.8)>.
2020-12-15 15:49:43,672 | INFO | Fetching package google-auth information from DB...
    self._target(*self._args, **self._kwargs)
  File "c:\python310\lib\multiprocessing\pool.py", line 519, in _handle_workers
2020-12-15 15:49:43,674 | INFO | Using cached info for package <Package Faker (4.18.0)>.
2020-12-15 15:49:43,673 | INFO | Using cached info for package <Package google-api-python-client (1.7.11)>.
    cls._wait_for_updates(current_sentinels, change_notifier)
2020-12-15 15:49:43,677 | INFO | Using cached info for package <Package protobuf (3.9.2)>.
2020-12-15 15:49:43,677 | INFO | Using cached info for package <Package fonttools (4.18.0)>.
2020-12-15 15:49:43,677 | INFO | Using cached info for package <Package urllib3 (1.24.2)>.
2020-12-15 15:49:43,674 | INFO | Fetching package google-auth-oauthlib information from DB...
2020-12-15 15:49:43,677 | INFO | Using cached info for package <Package google-auth (1.23.0)>.
2020-12-15 15:49:43,675 | INFO | Using cached info for package <Package setuptools (47.1.0)>.
  File "c:\python310\lib\multiprocessing\pool.py", line 499, in _wait_for_updates
2020-12-15 15:49:43,685 | INFO | Using cached info for package <Package google-auth-oauthlib (0.4.0)>.
    wait(sentinels, timeout=timeout)
  File "c:\python310\lib\multiprocessing\connection.py", line 884, in wait
    ready_handles = _exhaustive_wait(waithandle_to_obj.keys(), timeout)
  File "c:\python310\lib\multiprocessing\connection.py", line 816, in _exhaustive_wait
    res = _winapi.WaitForMultipleObjects(L, False, timeout)
ValueError: need at most 63 handles, got a sequence of length 66
```

**Comment by achillesrasquinha** [comment]
Seems like the number of cores used by pipupgrade is a ton! I'll lower the maximum fetch for this.

**Comment by RashiqAzhan** [comment]
Thank you for your work. I am excited to get to work with your new release.
